### ISSUE TITLE
ConstraintBasedEstimator, example code showed ValueError

### ISSUE THREAD

**Issue by chaconne70** [pgmpy/pgmpy#1004]
### Subject of the issue
ConstraintBasedEstimator - estimate(): example code showed ValueError

### Your environment
* pgmpy version: 0.1.6 
  (pgmpy-dev.zip, from https://github.com/pgmpy/pgmpy/tree/dev)
* Python version: 3.6.4
* Operating System: Windows

### Steps to reproduce
I used the example code, shown in http://pgmpy.org/estimators.html, 
estimate(significance_level=0.01)

import pandas as pd
import numpy as np
from pgmpy.estimators import ConstraintBasedEstimator
data = pd.DataFrame(np.random.randint(0, 5, size=(2500, 3)), columns=list('XYZ'))
data['sum'] = data.sum(axis=1)
print(data)
c = ConstraintBasedEstimator(data)
model = c.estimate()
print(model.edges()) 

### Expected behaviour
The example says, the result should be: [(‘Z’, ‘sum’), (‘X’, ‘sum’), (‘Y’, ‘sum’)]

### Actual behaviour
ValueError during model = c.estimate()

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    model = c.estimate()
  File "C:\Python36\lib\site-packages\pgmpy\estimators\ConstraintBasedEstimator.py", line 105, in estimate
    skel, separating_sets = self.estimate_skeleton(significance_level)
  File "C:\Python36\lib\site-packages\pgmpy\estimators\ConstraintBasedEstimator.py", line 181, in estimate_skeleton
    return self.build_skeleton(nodes, is_independent)
  File "C:\Python36\lib\site-packages\pgmpy\estimators\ConstraintBasedEstimator.py", line 528, in build_skeleton
    if is_independent(node, neighbor, separating_set):
  File "C:\Python36\lib\site-packages\pgmpy\estimators\ConstraintBasedEstimator.py", line 178, in is_independent
    chi2, p_value, sufficient_data = self.test_conditional_independence(X, Y, Zs)
  File "C:\Python36\lib\site-packages\pgmpy\estimators\base.py", line 241, in test_conditional_independence
    observed, expected = zip(*((o, e) for o, e in zip(observed, expected) if not e == 0))
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by ankurankan** [comment]
@chaconne70 Sorry for the late reply. Your code seems to be working for me. Could you please share the output of `pip freeze` in your environment?

**Comment by chaconne70** [comment]
related to some difference in environment, similar to #1004 issue? Anyway, I put the same pip freeze results here:
click==6.7
Cython==0.27.3
decorator==4.2.1
et-xmlfile==1.0.1
Flask==0.12.2
graphviz==0.8.3.dev0
itsdangerous==0.24
jdcal==1.3
Jinja2==2.10
libpgm==1.3
MarkupSafe==1.0
networkx==1.11
numpy==1.14.1
openpyxl==2.5.1
pandas==0.22.0
pgmpy==0.1.6
pyparsing==2.2.0
pyreadline==2.1
python-dateutil==2.6.1
pytz==2018.3
pywin32==221
scipy==1.0.0
six==1.11.0
Werkzeug==0.14.1
wrapt==1.10.11

**Comment by ankurankan** [comment]
@chaconne70 It seems you are getting the error because of a higher version of pandas. If you downgrade it to 0.19.1, it should work.

**Comment by chaconne70** [comment]
I tried, after changing pandas versions 0.19.2 and 0.19.1....
The 'ValueError' itself is resolved (no Error), and it estimates the correct structure for this simple case, 
  sum = X + Y + Z.
But, if I simply add one more variable, sum2 = Y + Z, i.e. add
    data['sum2'] = data['Y'] + data['Z']
the estimated structured is completely different to what is expected.....

So, the initial issue raised (ValueError) is resolved. But, estimated structure is not correct for simple cases...
