### ISSUE TITLE
Plotting of the Graphical Model

### ISSUE THREAD

**Issue by debadridtt** [pgmpy/pgmpy#1016]
### Subject of the issue
How to plot the probabilistic graphical model

Is there anyway I can plot the pgm diagram in python?

**Comment by khalibartan** [comment]
@debadridtt pgmpy uses networkx for graph structure, so you can use networkx for plotting the pgm graph.
```python
from pgmpy.models import BayesianModel
model = BayesianModel([('A', 'B'), ('B', 'C'), ('A', 'D'), ('D', 'C')])
import networkx as nx
import pylab as plt
nx.draw(model, with_labels=True)
plt.show()
```

**Comment by nav9** [comment]
@khalibartan: Thanks for the code, but it does not seem to work anymore due to ishold being deprecated:

> Traceback (most recent call last):
>   File "/media/nav/code/src/prog.py", line 88, in <module>
>     nx.draw(nounVerbModel, with_labels=True)
>   File "/home/nav/.local/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py", line 126, in draw
>     b = plt.ishold()
> AttributeError: module 'matplotlib.pyplot' has no attribute 'ishold'

Do you know of a fix for Python 3.6?

**Comment by khalibartan** [comment]
@nav9 In that case you might need to look at the networkx documentation on how you can plot graph. Though documentation still show same way for networkx. I'm not aware of any other easy ways for doing this.

**Comment by nav9** [comment]
Thanks. I just found the solution. It's due to a mismatch in the versions of networkx and matplotlib. It can also happen if there are multiple versions of matplotlib installed. If anyone else is facing the same issue, just uninstall all versions of matplotlib and networkx:
```console
sudo pip3 uninstall networkx
sudo pip3 uninstall matplotlib
python3 -mpip uninstall matplotlib
sudo conda uninstall matplotlib
```
If you've installed networkx via other sources like mpip or conda, uninstall via those too.

Then install both of them:
```console
sudo pip3 install networkx
sudo pip3 install matplotlib
```

Problem solved! There's nothing wrong with your code.

**Comment by AdeBC** [comment]
Thank you very much, this is exactly what I need!

**Comment by suprateembanerjee** [comment]
The code results in a StopIteration error on the sample posted above by @khalibartan. Tried @nav9 's solution. Did not work. Full trace:
```python
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
/Users/suprateembanerjee/Python Projects/CausalML/interventions.ipynb Cell 5' in <cell line: 5>()
      3 import networkx as nx
      4 import pylab as plt
----> 5 nx.draw(model, with_labels=True)
      6 plt.show()

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/networkx/drawing/nx_pylab.py:121, in draw(G, pos, ax, **kwds)
    118 if "with_labels" not in kwds:
    119     kwds["with_labels"] = "labels" in kwds
--> 121 draw_networkx(G, pos=pos, ax=ax, **kwds)
    122 ax.set_axis_off()
    123 plt.draw_if_interactive()

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/networkx/drawing/nx_pylab.py:304, in draw_networkx(G, pos, arrows, with_labels, **kwds)
    301     pos = nx.drawing.spring_layout(G)  # default to spring layout
    303 draw_networkx_nodes(G, pos, **node_kwds)
--> 304 draw_networkx_edges(G, pos, arrows=arrows, **edge_kwds)
    305 if with_labels:
    306     draw_networkx_labels(G, pos, **label_kwds)

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/networkx/drawing/nx_pylab.py:873, in draw_networkx_edges(G, pos, edgelist, width, edge_color, style, alpha, arrowstyle, arrowsize, edge_cmap, edge_vmin, edge_vmax, ax, arrows, label, node_size, nodelist, node_shape, connectionstyle, min_source_margin, min_target_margin)
    871 else:
    872     fancy_edges_indices = range(len(edgelist))
--> 873     edge_viz_obj = _draw_networkx_edges_fancy_arrow_patch()
    875 # update view after drawing
    876 padx, pady = 0.05 * w, 0.05 * h

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/networkx/drawing/nx_pylab.py:847, in draw_networkx_edges.<locals>._draw_networkx_edges_fancy_arrow_patch()
    832     arrow = mpl.patches.FancyArrowPatch(
    833         (x1, y1),
    834         (x2, y2),
   (...)
    843         zorder=1,
    844     )  # arrows go behind nodes
    846     arrow_collection.append(arrow)
--> 847     ax.add_patch(arrow)
    849 return arrow_collection

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/matplotlib/axes/_base.py:2363, in _AxesBase.add_patch(self, p)
   2361 if p.get_clip_path() is None:
   2362     p.set_clip_path(self.patch)
-> 2363 self._update_patch_limits(p)
   2364 self._children.append(p)
   2365 p._remove_method = self._children.remove

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/matplotlib/axes/_base.py:2381, in _AxesBase._update_patch_limits(self, patch)
   2378 if (isinstance(patch, mpatches.Rectangle) and
   2379         ((not patch.get_width()) and (not patch.get_height()))):
   2380     return
-> 2381 p = patch.get_path()
   2382 vertices = p.vertices if p.codes is None else p.vertices[np.isin(
   2383     p.codes, (mpath.Path.CLOSEPOLY, mpath.Path.STOP), invert=True)]
   2384 if not vertices.size:

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/matplotlib/patches.py:4446, in FancyArrowPatch.get_path(self)
   4443 """Return the path of the arrow in the data coordinates."""
   4444 # The path is generated in display coordinates, then converted back to
   4445 # data coordinates.
-> 4446 _path, fillable = self._get_path_in_displaycoord()
   4447 if np.iterable(fillable):
   4448     _path = Path.make_compound_path(*_path)

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/matplotlib/patches.py:4459, in FancyArrowPatch._get_path_in_displaycoord(self)
   4457     posB = self._convert_xy_units(self._posA_posB[1])
   4458     (posA, posB) = self.get_transform().transform((posA, posB))
-> 4459     _path = self.get_connectionstyle()(posA, posB,
   4460                                        patchA=self.patchA,
   4461                                        patchB=self.patchB,
   4462                                        shrinkA=self.shrinkA * dpi_cor,
   4463                                        shrinkB=self.shrinkB * dpi_cor
   4464                                        )
   4465 else:
   4466     _path = self.get_transform().transform_path(self._path_original)

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/networkx/drawing/nx_pylab.py:774, in draw_networkx_edges.<locals>._draw_networkx_edges_fancy_arrow_patch.<locals>._connectionstyle(posA, posB, *args, **kwargs)
    771     ret = mpl.path.Path(ax.transData.transform(path), [1, 4, 4, 4, 4, 4, 4])
    772 # if not, fall back to the user specified behavior
    773 else:
--> 774     ret = base_connection_style(posA, posB, *args, **kwargs)
    776 return ret

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/matplotlib/patches.py:2777, in ConnectionStyle._Base.__call__(self, posA, posB, shrinkA, shrinkB, patchA, patchB)
   2775 path = self.connect(posA, posB)
   2776 clipped_path = self._clip(path, patchA, patchB)
-> 2777 shrunk_path = self._shrink(clipped_path, shrinkA, shrinkB)
   2778 return shrunk_path

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/matplotlib/patches.py:2758, in ConnectionStyle._Base._shrink(self, path, shrinkA, shrinkB)
   2756 insideA = inside_circle(*path.vertices[0], shrinkA)
   2757 try:
-> 2758     left, path = split_path_inout(path, insideA)
   2759 except ValueError:
   2760     pass

File ~/miniforge3/envs/causalml/lib/python3.10/site-packages/matplotlib/bezier.py:352, in split_path_inout(path, inside, tolerance, reorder_inout)
    349 from .path import Path
    350 path_iter = path.iter_segments()
--> 352 ctl_points, command = next(path_iter)
    353 begin_inside = inside(ctl_points[-2:])  # true if begin point is inside
    355 ctl_points_old = ctl_points
```

**Comment by ankurankan** [comment]
@suprateembanerjee Sorry for the late reply, I missed the email. Yes, this seems to be an issue with the latest networkx and I don't see an easy fix for it. For now I think the easiest way would be to create a networkx graph from the model and plot that.
```python
from pgmpy.models import BayesianModel
model = BayesianModel([('A', 'B'), ('B', 'C'), ('A', 'D'), ('D', 'C')])
import networkx as nx
import pylab as plt
nx_graph = nx.DiGraph(model.edges())
nx.draw(nx_graph, with_labels=True)
plt.show()
```

**Comment by jonasvit** [comment]
When there is multiple variables in Bayesian network model, the nodes and their dependencies do not look good in the graphing... Any clue how to fix it?
![output](https://user-images.githubusercontent.com/89067278/212688470-a3c8fe0c-f99b-445a-9bd1-92f6b0ff902f.png)

**Comment by ankurankan** [comment]
@jonasvit You can have a look at networkx's drawing module (https://networkx.org/documentation/stable/reference/drawing.html)  for more controls on the plot. As pgmpy graphs inherit networkx's DiGraph all the methods should directly work for Bayesian Networks as well.

Another option for plotting is to use the daft package. pgmpy provides a function to directly convert Bayesian Network to a daft object. Here's an example, and the documentation is at https://pgmpy.org/base.html#pgmpy.base.DAG.DAG.to_daft:
```python
In [21]: from pgmpy.utils import get_example_model

In [22]: model = get_example_model('alarm')

In [23]: model.to_daft('circular', pgm_params={'grid_unit': 10}).render()
Out[23]: <Axes: >

```

**Comment by jonasvit** [comment]
Thank you @ankurankan! This is what I wanted.
