### ISSUE TITLE
Error in GibbsSampling.sample()

### ISSUE THREAD

**Issue by pmplant** [pgmpy/pgmpy#1017]
### Subject of the issue
GibbsSampling.sample() is non-functioning, provided example does not work.

### Your environment
* pgmpy version
Name: pgmpy
Version: 0.1.6

* Python version
Python 3.6.5

* Operating System
Linux
4.15.0-23-generic

### Steps to reproduce
Run the example code provided in the definition of GibbsSampling.sample()

```
from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import BayesianModel
from pgmpy.sampling import GibbsSampling

intel_cpd = TabularCPD('intel', 2, [[0.7], [0.3]])
sat_cpd = TabularCPD('sat', 2, [[0.95, 0.2], [0.05, 0.8]], evidence=['intel'], evidence_card=[2])
student = BayesianModel()
student.add_nodes_from(['intel', 'sat'])
student.add_edge('intel', 'sat')
student.add_cpds(intel_cpd, sat_cpd)
gibbs_chain = GibbsSampling(student)
gibbs_chain.sample(size=3)
```

### Expected behaviour
It should work

### Actual behaviour
It don't

```
Traceback (most recent call last):
  File "gibbexample.py", line 12, in <module>
    gibbs_chain.sample(size=3)
  File "/home/pmp/.local/lib/python3.6/site-packages/pgmpy/sampling/Sampling.py", line 382, in sample
    sampled[0] = np.array([st for var, st in self.state])
ValueError: setting an array element with a sequence.
```

**Comment by ankurankan** [comment]
Fixed.
