### ISSUE TITLE
to_junction_tree error

### ISSUE THREAD

**Issue by antocommi** [pgmpy/pgmpy#1034]
### Your environment
* pgmpy version 0.1.6
* Python version 3.7.0
* Operating System windows 10

### Steps to reproduce
Code:
`import pgmpy.readwrite.BIF
import matplotlib.pyplot as plt
import networkx as nx
from pgmpy.models import JunctionTree
from pgmpy.inference import BeliefPropagation

def main():
    reader = pgmpy.readwrite.BIF.BIFReader('model/asia.bif')
    model = reader.get_model()
    jtree = model.to_junction_tree()

if __name__ == '__main__':
    main()`
### Expected behaviour
calculate the junction tree 
### Actual behaviour
error: 
venv\lib\site-packages\pgmpy\models\MarkovModel.py", line 376, in _get_cliques_dict
    nodes=([node] + neighbors) )
TypeError: can only concatenate list (not "dict_keyiterator") to list

**Comment by antocommi** [comment]
This example, taken from documentation is also incorrect. Probably there is a bug in class BayesianModel
`from pgmpy.models import BayesianModel
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import BeliefPropagation

G = BayesianModel([('diff', 'grade'), ('intel', 'grade'),
                    ('intel', 'SAT'), ('grade', 'letter')])
diff_cpd = TabularCPD('diff', 2, [[0.2], [0.8]])
intel_cpd = TabularCPD('intel', 3, [[0.5], [0.3], [0.2]])
grade_cpd = TabularCPD('grade', 3,
                        [[0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                         [0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
                         [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]],
                        evidence=['diff', 'intel'],
                        evidence_card=[2, 3])
sat_cpd = TabularCPD('SAT', 2,
                      [[0.1, 0.2, 0.7],
                       [0.9, 0.8, 0.3]],
                      evidence=['intel'], evidence_card=[3])
letter_cpd = TabularCPD('letter', 2,
                         [[0.1, 0.4, 0.8],
                          [0.9, 0.6, 0.2]],
                         evidence=['grade'], evidence_card=[3])
G.add_cpds(diff_cpd, intel_cpd, grade_cpd, sat_cpd, letter_cpd)
bp = BeliefPropagation(G)
bp.calibrate()`


the error generated is below:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users//PycharmProjects/baystest/MyBaysNet/test22.py", line 24, in <module>
    bp = BeliefPropagation(G)
  File "C:\Users\\PycharmProjects\baystest\venv\lib\site-packages\pgmpy\inference\ExactInference.py", line 323, in __init__
    self.junction_tree = model.to_junction_tree()
  File "C:\Users\\PycharmProjects\baystest\venv\lib\site-packages\pgmpy\models\BayesianModel.py", line 643, in to_junction_tree
    return mm.to_junction_tree()
  File "C:\Users\\PycharmProjects\baystest\venv\lib\site-packages\pgmpy\models\MarkovModel.py", line 503, in to_junction_tree
    clique_trees = JunctionTree(nx.minimum_spanning_tree(complete_graph).edges())
  File "C:\Users\\PycharmProjects\baystest\venv\lib\site-packages\networkx\algorithms\tree\mst.py", line 547, in minimum_spanning_tree
    T.add_nodes_from(G.nodes.items())
  File "C:\Users\\PycharmProjects\baystest\venv\lib\site-packages\pgmpy\base\UndirectedGraph.py", line 145, in add_nodes_from
    self.add_node(node=node)
  File "C:\Users\\PycharmProjects\baystest\venv\lib\site-packages\pgmpy\base\UndirectedGraph.py", line 100, in add_node
    super(UndirectedGraph, self).add_node(node, weight=weight)
  File "C:\Users\\PycharmProjects\baystest\venv\lib\site-packages\networkx\classes\graph.py", line 499, in add_node
    if node_for_adding not in self._node:
TypeError: unhashable type: 'dict'

**Comment by dddpt** [comment]
Got the same error, trying to transform a BayesianModel into a junction tree. Only difference in setup is I'm using Mac OS 10.13.6.
The bug seems to come from the fact that when the BayesianModel is turned into a UndirectedGraph, a dict shows up in composite nodes' identifying tuples, making those unhashable.

**Comment by ghost** [comment]
Worked around this by reverting to networkx 1.11.

**Comment by dddpt** [comment]
Thanks for the workaround! It indeed allows BeliefPropagation to work.

Note however that it's only a workaround. In my case, 1.11 breaks usages of the networkx "nodes" attributes. Apparently BayesianModel.nodes is a bound method instead of an instance variable in networkx 1.11.

**Comment by ankurankan** [comment]
Fixed in #1056, 94ae440, d4761e5. Should work for latest networkx now.
