### ISSUE TITLE
nosetests failed

### ISSUE THREAD

**Issue by dynaryu** [pgmpy/pgmpy#1043]
### Subject of the issue
nose tests failed at OS X

### Your environment
* pgmpy version 0.1.6 
* Python version 3.5.5
* Operating System OS X

### Steps to reproduce
nosetests -v 

### Actual behaviour

There were a bunch of numpy related error such as can not import name multiarray.

======================================================================
FAIL: test_add_edge_string (pgmpy.tests.test_base.test_DirectedGraph.TestDirectedGraphCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hyeuk/anaconda2/envs/pymc3/lib/python3.5/site-packages/pgmpy/tests/test_base/test_DirectedGraph.py", line 52, in test_add_edge_string
    self.assertListEqual(self.graph.edges(), [('d', 'e')])
AssertionError: First sequence is not a list: OutEdgeView([('d', 'e')])

======================================================================
FAIL: test_add_node_string (pgmpy.tests.test_base.test_DirectedGraph.TestDirectedGraphCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hyeuk/anaconda2/envs/pymc3/lib/python3.5/site-packages/pgmpy/tests/test_base/test_DirectedGraph.py", line 24, in test_add_node_string
    self.assertListEqual(self.graph.nodes(), ['a'])
AssertionError: First sequence is not a list: NodeView(('a',))

======================================================================
FAIL: test_update_node_parents (pgmpy.tests.test_base.test_DirectedGraph.TestDirectedGraphCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hyeuk/anaconda2/envs/pymc3/lib/python3.5/site-packages/pgmpy/tests/test_base/test_DirectedGraph.py", line 98, in test_update_node_parents
    self.assertListEqual(self.graph.predecessors('a'), [])
AssertionError: First sequence is not a list: <dictionary-keyiterator object at 0x108049e68>

======================================================================
FAIL: test_update_node_parents_bm_constructor (pgmpy.tests.test_base.test_DirectedGraph.TestDirectedGraphCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hyeuk/anaconda2/envs/pymc3/lib/python3.5/site-packages/pgmpy/tests/test_base/test_DirectedGraph.py", line 91, in test_update_node_parents_bm_constructor
    self.assertListEqual(self.graph.predecessors('a'), [])
AssertionError: First sequence is not a list: <dictionary-keyiterator object at 0x108049e68>

======================================================================
FAIL: test_add_node_nonstring (pgmpy.tests.test_base.test_UndirectedGraph.TestUndirectedGraphCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hyeuk/anaconda2/envs/pymc3/lib/python3.5/site-packages/pgmpy/tests/test_base/test_UndirectedGraph.py", line 27, in test_add_node_nonstring
    self.assertListEqual(self.graph.nodes(), [1])
AssertionError: First sequence is not a list: NodeView((1,))

======================================================================
FAIL: test_add_node_string (pgmpy.tests.test_base.test_UndirectedGraph.TestUndirectedGraphCreation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hyeuk/anaconda2/envs/pymc3/lib/python3.5/site-packages/pgmpy/tests/test_base/test_UndirectedGraph.py", line 23, in test_add_node_string
    self.assertListEqual(self.graph.nodes(), ['a'])
AssertionError: First sequence is not a list: NodeView(('a',))

----------------------------------------------------------------------

**Comment by ankurankan** [comment]
This is because of using a newer version of `networkx`. Please try downgrading it to 0.19.2 and it should work.
