### ISSUE TITLE
Name for pytorch in requirements.txt is wrong

### ISSUE THREAD

**Issue by daanknoope** [pgmpy/pgmpy#1101]
### Subject of the issue
In the requirements file, `pytorch` is mentioned, but pip throws an error that this should be `torch`. 

### Your environment
* pgmpy version: 0.1.7 (72dbc78, DEV)
* Python version: 3.7.2
* Operating System: Ubuntu 18.04.2 

### Steps to reproduce
1. Run `pip install -r requirements.txt`

### Expected behaviour
The required packages should be installed without error message.

### Actual behaviour
Pip returns:
```python
Building wheels for collected packages: pytorch
  Running setup.py bdist_wheel for pytorch ... error
  Complete output from command /home/daan/anaconda3/envs/rm/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-e8ywvbqp/pytorch/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ve3gtmj_ --python-tag cp37:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-e8ywvbqp/pytorch/setup.py", line 15, in <module>
      raise Exception(message)
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"

```

**Comment by bpshaver** [comment]
For some reason, this hasn't been fixed yet. For anyone else seeing this issue in the future, you may replace "pytorch" with "torch" in the `requirements.txt` like so:

```
git clone https://github.com/pgmpy/pgmpy \
&& cd pgmpy/ \
&& sed -i 's/pytorch/torch/' requirements.txt \
&& pip install -r requirements.txt \
&& python setup.py install
```

(Written as one command for the purposes of a Dockerfile)

**Comment by ankurankan** [comment]
@bpshaver The problem is that pypi and anaconda have different package names for pytorch.
