### ISSUE TITLE
ImportError: cannot import name 'MmhcEstimator' from 'pgmpy.estimators'

### ISSUE THREAD

**Issue by Maple961105** [pgmpy/pgmpy#1152]
### Subject of the issue
hi,I am a beginner.I want konw  how to do with this

### Your environment
* pgmpy version 0.1.6
* Python version 3.7
* Operating System windows

**Comment by ankurankan** [comment]
@Maple961105 The MMHC Estimator is not implemented yet. There is an open PR for it: https://github.com/pgmpy/pgmpy/pull/721 which you might be able to use.

**Comment by zhp66** [comment]
Traceback (most recent call last):
  File "C:/Users/58413/PycharmProjects/topology/structure learning3.py", line 21, in <module>
    skeleton = mmhc.mmpc()
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 180, in mmpc
    new_neighbor, new_neighbor_min_assoc = max_min_heuristic(node, neighbors[node])
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 166, in max_min_heuristic
    min_assoc_val = min_assoc(X, Y, Zs)
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 158, in min_assoc
    return min(assoc(X, Y, Zs_subset) for Zs_subset in powerset(Zs))
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 158, in <genexpr>
    return min(assoc(X, Y, Zs_subset) for Zs_subset in powerset(Zs))
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 154, in assoc
    return 1 - self.test_conditional_independence(X, Y, Zs)[1]
TypeError: 'bool' object is not subscriptable

**Comment by ankurankan** [comment]
@zhp66 We have recently changed the `test_conditional_independence` method to only return a boolean based on the `p_value`. A simple hack to make this work would be to directly call `pgmpy.estimators.CITests.chi_square` with an additional `data` argument instead of the `test_conditional_independence`.

**Comment by zhp66** [comment]
def assoc(X, Y, Zs):
            """Measure for (conditional) association between variables. Use negative
            p-value of independence test.
            """
            return 1 - self.test_conditional_independence(X, Y, Zs)[1]

How to use test_conditional_independence here？MMHC Algorithm cannot work

**Comment by ankurankan** [comment]
@zhp66 Try replacing return `1 - self.test_conditional_independence(X, Y, Zs)[1]` with `return 1 - CITests.chi_square(X, Y, Zs, self.data)[1]`. Also `is_independent` in https://github.com/pgmpy/pgmpy/pull/721/files#diff-5bb2593c4c7e6901df8bc572be120bb7R190 will need to be replaced with `self.test_conditional_independence(X, Y, Zs)`

**Comment by zhp66** [comment]
Thank you, but after I did........

Traceback (most recent call last):
  File "C:/Users/58413/PycharmProjects/topology/3.py", line 9, in <module>
    model = est.estimate()
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 75, in estimate
    skel = self.mmpc(significance_level)
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 181, in mmpc
    new_neighbor, new_neighbor_min_assoc = max_min_heuristic(node, neighbors[node])
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 167, in max_min_heuristic
    min_assoc_val = min_assoc(X, Y, Zs)
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 159, in min_assoc
    return min(assoc(X, Y, Zs_subset) for Zs_subset in powerset(Zs))
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 159, in <genexpr>
    return min(assoc(X, Y, Zs_subset) for Zs_subset in powerset(Zs))
  File "C:\Users\58413\PycharmProjects\topology\MmhcEstimator.py", line 155, in assoc
    return 1 - CITests.chi_square(X, Y, Zs, self.data)[1] #self.test_conditional_independence(X, Y, Zs)[1]
  File "C:\Anaconda3\lib\site-packages\pgmpy\estimators\CITests.py", line 77, in chi_square
    state_names = kwargs["state_names"]
KeyError: 'state_names'

**Comment by ankurankan** [comment]
@zhp66 I fixed all the errors in this branch: https://github.com/ankurankan/pgmpy/tree/pr/721. But I haven't checked if the algorithm is giving the correct outputs, so please verify that if you are using it.

**Comment by zhp66** [comment]
Thank you very much. The problem has been solved
