### ISSUE TITLE
Inference fails for disconnected graphs in v0.19

### ISSUE THREAD

**Issue by thomast8** [pgmpy/pgmpy#1205]
### Subject of the issue
Variable Elimination and Belief Propagation worked fine in v0.18 but are broken in v0.19 for a specific graph I am using.
I'm quite sure the issue is due to the fact that the graphs have disconnected components.
When running `query()` on the resulting object, I receive the following errors, if using VariableElimination or BeliefPropagation:
```
Finding Elimination Order: :   0%|                                                                                                                                                                             | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/networkx/classes/graph.py", line 623, in remove_node
    nbrs = list(adj[n])  # list handles self-loops (allows mutation)
KeyError: 'lateralita'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/thomastiotto/Documents/University/USI/Thesis/xai/core/main.py", line 169, in <module>
    model.plot_model( independenciesplot=False, showconnectedness=True )
  File "/Users/thomastiotto/Documents/University/USI/Thesis/xai/core/bayesian.py", line 584, in plot_model
    connectedness = self.mutual_information( parent.name, child.name, self.evidence)
  File "/Users/thomastiotto/Documents/University/USI/Thesis/xai/core/bayesian.py", line 623, in mutual_information
    joint =  model_infer.query( variables=[X, Y], evidence=evidence, joint=True )
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/pgmpy/inference/ExactInference.py", line 254, in query
    show_progress=show_progress,
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/pgmpy/inference/ExactInference.py", line 161, in _variable_elimination
    variables, evidence, elimination_order, show_progress=show_progress
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/pgmpy/inference/ExactInference.py", line 108, in _get_elimination_order
    ).get_elimination_order(nodes=to_eliminate, show_progress=show_progress)
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/pgmpy/inference/EliminationOrder.py", line 100, in get_elimination_order
    self.moralized_model.remove_node(min_score_node)
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/networkx/classes/graph.py", line 626, in remove_node
    raise NetworkXError("The node %s is not in the graph." % (n,))
networkx.exception.NetworkXError: The node lateralita is not in the graph.
Finding Elimination Order: :   0%|                                                                                                                                                                             | 0/10 [00:00<?, ?it/s]

Process finished with exit code 1
```
```
Traceback (most recent call last):
  File "/Users/thomastiotto/Documents/University/USI/Thesis/xai/core/main.py", line 169, in <module>
    model.plot_model( independenciesplot=False, showconnectedness=True )
  File "/Users/thomastiotto/Documents/University/USI/Thesis/xai/core/bayesian.py", line 584, in plot_model
    connectedness = self.mutual_information( parent.name, child.name, self.evidence)
  File "/Users/thomastiotto/Documents/University/USI/Thesis/xai/core/bayesian.py", line 620, in mutual_information
    model_infer = BeliefPropagation( self.model_pgmpy )
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/pgmpy/inference/ExactInference.py", line 473, in __init__
    self.junction_tree = model.to_junction_tree()
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/pgmpy/models/BayesianModel.py", line 466, in to_junction_tree
    mm = self.to_markov_model()
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/pgmpy/models/BayesianModel.py", line 425, in to_markov_model
    mm.add_factors(*[cpd.to_factor() for cpd in self.cpds])
  File "/Users/thomastiotto/.conda/envs/python_37/lib/python3.7/site-packages/pgmpy/models/MarkovModel.py", line 143, in add_factors
    raise ValueError("Factors defined on variable not in the model", factor)
ValueError: ('Factors defined on variable not in the model', <DiscreteFactor representing phi(eta arrotondata:3) at 0xa1b5672d0>)

Process finished with exit code 1
```

The DOT representation BN graph is the following and, as can be seen, the disconnected components "lateralita" and "eta arrotondata" are involved in the issue:
```// 43461175088
graph "../graphs/bayesian_net" {
	"eta arrotondata" [label="eta arrotondata"]
	lateralita [label=lateralita]
	situ [label=situ]
	morfologia [label=morfologia]
	pT [label=pT]
	pN [label=pN]
	pM [label=pM]
	differenziazione [label=differenziazione]
	"recettori estrogeni" [label="recettori estrogeni"]
	"recettori progestinici" [label="recettori progestinici"]
	"c erbB 2" [label="c erbB 2"]
	ki67 [label=ki67]
	pN -- situ [label=0.01 penwidth=0.0962257412349095]
	"recettori estrogeni" -- morfologia [label=0.02 penwidth=0.15498588900089924]
	pN -- pT [label=0.13 penwidth=1.3424777074755068]
	pM -- pT [label=0.08 penwidth=0.8411423732841505]
	pM -- pN [label=0.03 penwidth=0.3251294398072941]
	pN -- differenziazione [label=0.01 penwidth=0.14217307360734435]
	"recettori estrogeni" -- differenziazione [label=0.11 penwidth=1.0788063636645542]
	"recettori estrogeni" -- "recettori progestinici" [label=0.14 penwidth=1.3568877663398615]
	differenziazione -- "c erbB 2" [label=0.05 penwidth=0.5022816255736706]
	"recettori estrogeni" -- "c erbB 2" [label=0.04 penwidth=0.4099416248226981]
	differenziazione -- ki67 [label=0.23 penwidth=2.3115923883385014]
	"recettori estrogeni" -- ki67 [label=0.11 penwidth=1.1111918859237981]
	label="\n\nBayesian Network structure\nMutual information shown on edges (not for variables in evidence)"
}
```

### Your environment
* pgmpy version: v0.19
* Python version: 3.7
* Operating System: MacOS 10.15.1

### Steps to reproduce
```
from pgmpy.inference import VariableElimination
model_infer = VariableElimination( self.model_pgmpy )
joint =  model_infer.query( variables=[X, Y], evidence=evidence, joint=True )
```

### Expected behaviour
Correct query result should be returned

### Actual behaviour
Issue thrown by NetworkX or MarkovModel

**Comment by ankurankan** [comment]
@Tioz90 Thanks for reporting this. Has been fixed in the latest dev.
