### ISSUE TITLE
Importing BayesianModel raises ValueError 

### ISSUE THREAD

**Issue by terodea** [pgmpy/pgmpy#1254]
### Subject of the issue
Import of the Bayesian Model raises ValueError. However, 0.1.9 release I could easily import without any error. 

### Your environment
* pgmpy==0.1.10dev
* Python 3.5.2
* Operating System Ubuntu 16.04

### Steps to reproduce
`from pgmpy.models import BayesianModel`

### Expected behavior
The import of Bayseian Model shouldn't raise ValueError. 

### Actual behavior
`>>> from pgmpy.models import BayseianModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/pgmpy-0.1.10.dev0-py3.5.egg/pgmpy/models/__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/pgmpy-0.1.10.dev0-py3.5.egg/pgmpy/models/BayesianModel.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/pgmpy-0.1.10.dev0-py3.5.egg/pgmpy/factors/discrete/__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1096, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 533, in spec_from_file_location
  File "/usr/local/lib/python3.5/dist-packages/pgmpy-0.1.10.dev0-py3.5.egg/pgmpy/factors/discrete/DiscreteFactor.py", line 431
    raise ValueError(f"The variable: {var} is not in the factor")
                                                               ^
SyntaxError: invalid syntax
`

**Comment by ankurankan** [comment]
@terodea The error is because of the version of python you are using. pgmpy only supports python 3.6 or higher. Upgrading python would fix this.

**Comment by terodea** [comment]
@ankurankan Thanks for the suggestion.
