### ISSUE TITLE
IndexError: number of dimensions must be within [0, 32], indexing result would have 33

### ISSUE THREAD

**Issue by Ketki-Savle** [pgmpy/pgmpy#1265]
### Subject of the issue
Describe your issue here.

### Your environment
* pgmpy version : latest
* Python version: 3.6
* Operating System: MacOS

### Steps to reproduce
length of tuple list is 885
length of nodes 410
length of input data columns 4211

### Expected behaviour
Model.predict does not return correct values. 

### Actual behaviour
full trace: 

"""
Traceback (most recent call last):
  File "/Users/ag33366/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/Users/ag33366/anaconda3/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/Users/ag33366/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/Users/ag33366/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/Users/ag33366/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/ag33366/pgmpy/pgmpy/inference/ExactInference.py", line 370, in map_query
    show_progress=show_progress,
  File "/Users/ag33366/pgmpy/pgmpy/inference/ExactInference.py", line 195, in _variable_elimination
    return factor_product(*final_distribution).normalize(inplace=False)
  File "/Users/ag33366/pgmpy/pgmpy/factors/base.py", line 70, in factor_product
    return reduce(lambda phi1, phi2: phi1 * phi2, args)
  File "/Users/ag33366/pgmpy/pgmpy/factors/base.py", line 70, in <lambda>
    return reduce(lambda phi1, phi2: phi1 * phi2, args)
  File "/Users/ag33366/pgmpy/pgmpy/factors/discrete/DiscreteFactor.py", line 825, in __mul__
    return self.product(other, inplace=False)
  File "/Users/ag33366/pgmpy/pgmpy/factors/discrete/DiscreteFactor.py", line 617, in product
    phi.values = phi.values[tuple(slice_)]
IndexError: number of dimensions must be within [0, 32], indexing result would have 33
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bayesian_diag_to_symptom.py", line 84, in <module>
    y_pred = diabetic_model.predict(predict_data)
  File "/Users/ag33366/pgmpy/pgmpy/models/BayesianModel.py", line 589, in predict
    data_unique.iterrows(), total=data_unique.shape[0]
  File "/Users/ag33366/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1017, in __call__
    self.retrieve()
  File "/Users/ag33366/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 909, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/ag33366/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 562, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/ag33366/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/ag33366/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
IndexError: number of dimensions must be within [0, 32], indexing result would have 33

**Comment by ankurankan** [comment]
@Ketki-Savle Thanks for reporting this. I am guessing you are trying to do inference? In this case, the inference algorithm is creating intermediate factors that involve more than 32 variables. Since factors are represented using a n-dimensional array internally and numpy has a limit of max 32 dimensions, this throws an error. I would suggest reducing the complexity of your model structure or specifying an elimination order which would avoid the creation of huge factors.

**Comment by Ketki-Savle** [comment]
Hey Ankur, 

Thank you for your quick response. Truly appreciate the open source support. 

Yes this is for inference and for predict function. So I have 9 parents and 477 children nodes. If we want to  reduce the complexity, could you please throw some number, May be 9 parents with 32 children if I understood your point correct? 

And I also checked another issue where latency in prediction has been reported. As per your suggestion, I have removed all duplicate records but still model.predict is extremely slow. 

Another question is, what is the scope of scaling your code? If you could point me towards the program modules which I can modify if possible, I am happy to see if we can scale this solution for more than 32 nodes. 

And last but not the least, This is a great implementation and very thorough! Plus the documentation and tutorials. Thank you for making this open source.  :) 

Regards, 

Ketki

**Comment by ankurankan** [comment]
@Ketki-Savle If you have a structure with 9 parents and multiple children and edges only between parent and child, I think it should be computationally efficient if you provide the elimination order as: `[child nodes, parent nodes]`. This should avoid creating huge factors and should work for even 477 children. In general, for removing each non-query variable during inference (variable elimination), you need to multiply all the CPDs that involve that variable, hence the computational complexity is exponential.

The complexity problem is not per se in the implementation but is rather because of the exponential nature of probability distributions. A single distribution with 32 variables, with each variable having just 2 states has 2**32 values which would require 32GBs of memory if using double-precision float. So, it is just not feasible to work with such huge distributions given our computational limits.

**Comment by Ketki-Savle** [comment]
Where can I change this elimination order? Thank you.
