### ISSUE TITLE
Tests failing because Travis can't find isclose method of numpy

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#128]
``` python3
Traceback (most recent call last):
  File "/home/travis/build/pgmpy/pgmpy/pgmpy/tests/test_Factor.py", line 292, in setUp
    self.jpd = JPD(['x1', 'x2', 'x3'], [2, 3, 2], values=np.ones(12)/12)
  File "/home/travis/build/pgmpy/pgmpy/pgmpy/Factor/JointProbabilityDistribution.py", line 75, in __init__
    if np.isclose(np.sum(values), 1):
AttributeError: 'module' object has no attribute 'isclose'
```

@abinashpanda Could you please look into it? I couldn't find anything.

**Comment by ankurankan** [comment]
Fixed
