### ISSUE TITLE
I find a issue for pgmpy of LinearGaussianCPD

### ISSUE THREAD

**Issue by JZQ-Coder** [pgmpy/pgmpy#1325]
### Subject of the issue
this is my code,I hope to build a GaussianBayesianNetwork,but i find model has no attribute 'scope'.
So please help me,how to solve it
```python
from pgmpy.models import *
import pandas as pd
model = LinearGaussianBayesianNetwork([('hist_dist', 'dist_relevance'),('curr_dist', 'dist_relevance'),('monthly_exp','offer_interest'),('cat_merchant_affinity','offer_interest'),
('offer_interest','offer_hit_effect'),('dist_relevance','offer_hit_effect')])

model.add_nodes_from(['hist_dist', 'curr_dist', 'dist_relevance','monthly_exp','cat_merchant_affinity','offer_interest','offer_hit_effect'])

from pgmpy.factors.continuous import LinearGaussianCPD

hist_dist_cpd = LinearGaussianCPD('hist_dist', [200], 20)
curr_dist_cpd = LinearGaussianCPD('curr_dist', [400], 50)
dist_rel_cpd = LinearGaussianCPD('dist_relevance', [0, 0.5, 0.5], 0.1, ['hist_dist', 'curr_dist'])

monthly_exp_cpd = LinearGaussianCPD('monthly_exp', [45000], 5000)
cat_merchant_cpd = LinearGaussianCPD('cat_merchant_affinity', [0.6], 0.2)
offer_interest_cpd = LinearGaussianCPD('offer_interest', [0, 0.7, 0.3], 0.1, ['monthly_exp', 'cat_merchant_affinity'])

offer_hit_effect_cpd = LinearGaussianCPD('offer_hit_effect', [0.1, 0.3, 0.6], 0.2, ['dist_relevance', 'offer_interest'])
model.add_cpds(hist_dist_cpd, curr_dist_cpd, dist_rel_cpd, monthly_exp_cpd, cat_merchant_cpd, offer_interest_cpd, offer_hit_effect_cpd)

A = pd.DataFrame(data=[[1, 1, -3, 1, 0, 1]], columns=['hist_dist', 'curr_dist', 'monthly_exp', 'cat_merchant_affinity', 'dist_relevance', 'offer_interest'])
model.predict_probability(A)
```

### Your environment
* 0.1.11
* 3.7
* Win10

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

### Expected behaviour
Tell us what should happen

### Actual behaviour
```python
Traceback (most recent call last):
  File "F:/Python/PythonWorkSpace/BayesNet/a.py", line 22, in <module>
    model.predict_probability(A)
  File "F:\Python\Anaconda\Anaconda3\lib\site-packages\pgmpy\models\BayesianModel.py", line 651, in predict_probability
    model_inference = VariableElimination(self)
  File "F:\Python\Anaconda\Anaconda3\lib\site-packages\pgmpy\inference\base.py", line 76, in __init__
    for var in cpd.scope():
AttributeError: 'LinearGaussianCPD' object has no attribute 'scope'
```

**Comment by theUltraMarine19** [comment]
Cross linking the pull-request for fix : #962

**Comment by Nimish-4** [comment]
Fixed.
