### ISSUE TITLE
DynamicBayesianNetwork limitations

### ISSUE THREAD

**Issue by nihil21** [pgmpy/pgmpy#1340]
### Subject of the issue
From what I've understood, in `pgmpy` it's possible to define `DynamicBayesianNetwork`'s edges only in the first time slice (as in #714); so, to define a DBN as the following:

![immagine](https://user-images.githubusercontent.com/15859553/95138716-3068c600-076b-11eb-8912-0ed8c3aa6863.png)

I would need to add the edges in the first time slice, like this:

![immagine](https://user-images.githubusercontent.com/15859553/95139073-f4823080-076b-11eb-92b6-214280b436a6.png)

However, by doing so I would create a loop, and thus `pgmpy` throws an error.

In my opinion, forcing to define edges in the first time slice is very limiting: functional loops over time are [a desired property](https://synergy.st-andrews.ac.uk/vannesmithlab/research/bayesian-networks/) of DBN, but in this way we lose such property.

**Comment by ankurankan** [comment]
@nihil21 Yes, I agree with you. DBNs haven't been my main focus as you can see with the number of bugs. But if you would like to contribute something like this, you are most welcome and I think it would be very interesting and useful.

**Comment by FelipeGiro** [comment]
@ankurankan I can work on this. Could you assign me?

**Comment by FelipeGiro** [comment]
### The code. 

A DBN with functional loop:

```
import numpy as np
from scipy.special import softmax
from pgmpy.models import DynamicBayesianNetwork
from pgmpy.inference import DBNInference
from pgmpy.factors.discrete import TabularCPD

edges=[
( ('A', 0) , ('A', 1) ),
( ('A', 0) , ('B', 1) ),
( ('B', 0) , ('B', 1) ),
( ('B', 0) , ('C', 1) ),
( ('C', 0) , ('A', 1) ),
( ('C', 0) , ('C', 1) )
]

bnet=DynamicBayesianNetwork(edges)#, latents=set('L'))

bnet_cpds = []
bnet_cpds.append(
    TabularCPD(('A', 0), 2, softmax(np.ones((2,1)), axis=0)))
bnet_cpds.append(
    TabularCPD(('B', 0), 2, softmax(np.ones((2,1)), axis=0)))
bnet_cpds.append(
    TabularCPD(('C', 0), 2, softmax(np.ones((2,1)), axis=0)))
bnet_cpds.append(
    TabularCPD(('A', 1), 2, softmax(np.ones((2,4)), axis=0), evidence=[('A', 0), ('C', 0)], evidence_card=[2,2]))
bnet_cpds.append(
    TabularCPD(('B', 1), 2, softmax(np.ones((2,4)), axis=0), evidence=[('A', 0), ('B', 0)], evidence_card=[2,2]))
bnet_cpds.append(
    TabularCPD(('C', 1), 2, softmax(np.ones((2,4)), axis=0), evidence=[('B', 0), ('C', 0)], evidence_card=[2,2]))

bnet.add_cpds(*bnet_cpds)
ie=DBNInference(bnet)
```

### The error:

```
Traceback (most recent call last):
  File "c:/Developments/test.py", line 34, in <module>
    ie=DBNInference(bnet)
  File "c:\developments\pgmpy\pgmpy\inference\dbn_inference.py", line 59, in __init__      
    self._initialize_structures()
  File "c:\developments\pgmpy\pgmpy\inference\base.py", line 105, in _initialize_structures
    self.start_bayesian_model.add_cpds(*self.model.get_cpds(time_slice=0))
  File "c:\developments\pgmpy\pgmpy\models\BayesianNetwork.py", line 258, in add_cpds
    raise ValueError("CPD defined on variable not in the model", cpd)
ValueError: ('CPD defined on variable not in the model', <TabularCPD representing P(('A', 0):2) at 0x16013c1aac8>)
```

### Issue

`self.nodes()` returns `NodeView(())`  in:

https://github.com/pgmpy/pgmpy/blob/6bf4b35dacad88bab2a1be3e394dfdbdd39e53ae/pgmpy/models/BayesianNetwork.py#L257-L258

So, whatever the value for `cpd.scope()`, will always raise an error.

### Questions
@ankurankan 

1. Where exactly `self.nodes()` is defined? I think the problem is related to the nodes creation, but I cannot see where it is generated.
2. Why if I run `bnet.nodes()` right after initalizating the DBN, all nodes will be there?

`NodeView((<DynamicNode(A, 0) at 0x1639a532b48>, <DynamicNode(A, 1) at 0x1639a532d08>, <DynamicNode(B, 1) at 0x1639a532b08>, <DynamicNode(B, 0) at 0x1639a532d88>, <DynamicNode(C, 1) at 0x1639a532e08>, <DynamicNode(C, 0) at 0x1639a532e48>))`

**Comment by ankurankan** [comment]
@FelipeGiro Are you using the latest `dev` branch? Because I am not able to reproduce the error. Your code snippet works fine on my machine. 

The `nodes` method btw is from networkx.DiGraph.

**Comment by FelipeGiro** [comment]
My mistake, I forgot one line of code: `ie=DBNInference(bnet)`. I just updated my previous comment.

I did not notice `BayesianNetwork` is called by `DBNInference` instead of `DynamicBayesianNetwork`.

**Comment by ankurankan** [comment]
@FelipeGiro I looked at this issue and I think if we replace the Bayesian model creation before inference here: https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/inference/base.py#L104 with calls to  `DynamicBayesianNetwork.get_const_bn`, then it should work fine. What do you think?
