### ISSUE TITLE
Installing pgmpy using pip requires pytorch to be installed

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#1393]
### Subject of the issue
Installing pgmpy using pip and import pgmpy throws an error that torch not found. This shouldn't be the case as pytorch is an optional dependency and should only throw an error if some relevant function gets called.

**Comment by smithsophia1688** [comment]
I am running into the same issue. When I run:  `pip install pgmpy` I get the following error: 

```
WARNING: The candidate selected for download or install is a yanked version: 'torch' candidate (version 0.1.2.post2 at https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz#sha256=a43e37f8f927c5b18f80cd163daaf6a1920edafcab5102e02e3e14bb97d9c874 (from https://pypi.org/simple/torch/))
Reason for being yanked: 0.1.2 is past it's support date and confuses users on unsupported platforms
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\smith_5\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-4063trmq\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-4063trmq\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\smith_5\AppData\Local\Temp\pip-wheel-ajtlosv3'
       cwd: C:\Users\smith_5\AppData\Local\Temp\pip-install-4063trmq\torch\
```

**Comment by ankurankan** [comment]
@smithsophia1688 This doesn't seem to be because of pgmpy. Could you maybe share the complete traceback of the error that you are getting?

**Comment by smithsophia1688** [comment]
Here is the full print out when I run: pip install pgmpy


```
Collecting pgmpy
  Using cached pgmpy-0.1.14-py3-none-any.whl (331 kB)
Requirement already satisfied: scikit-learn in c:\users\smith_5\anaconda3\lib\site-packages (from pgmpy) (0.23.1)
Requirement already satisfied: pandas in c:\users\smith_5\anaconda3\lib\site-packages (from pgmpy) (1.1.3)
Requirement already satisfied: statsmodels in c:\users\smith_5\anaconda3\lib\site-packages (from pgmpy) (0.12.0)
Requirement already satisfied: tqdm in c:\users\smith_5\anaconda3\lib\site-packages (from pgmpy) (4.50.2)
Requirement already satisfied: scipy in c:\users\smith_5\anaconda3\lib\site-packages (from pgmpy) (1.5.2)
Requirement already satisfied: pyparsing in c:\users\smith_5\anaconda3\lib\site-packages (from pgmpy) (2.4.7)
Requirement already satisfied: joblib in c:\users\smith_5\anaconda3\lib\site-packages (from pgmpy) (0.17.0)
Requirement already satisfied: numpy in c:\users\smith_5\anaconda3\lib\site-packages (from pgmpy) (1.19.2)
Collecting torch
  Using cached torch-0.1.2.post2.tar.gz (128 kB)
Requirement already satisfied: networkx in c:\users\smith_5\anaconda3\lib\site-packages (from pgmpy) (2.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\smith_5\anaconda3\lib\site-packages (from scikit-learn->pgmpy) (2.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\smith_5\anaconda3\lib\site-packages (from pandas->pgmpy) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\smith_5\anaconda3\lib\site-packages (from pandas->pgmpy) (2020.1)
Requirement already satisfied: patsy>=0.5 in c:\users\smith_5\anaconda3\lib\site-packages (from statsmodels->pgmpy) (0.5.1)
Requirement already satisfied: pyyaml in c:\users\smith_5\anaconda3\lib\site-packages (from torch->pgmpy) (5.3.1)
Requirement already satisfied: decorator>=4.3.0 in c:\users\smith_5\anaconda3\lib\site-packages (from networkx->pgmpy) (4.4.2)
Requirement already satisfied: six>=1.5 in c:\users\smith_5\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->pgmpy) (1.15.0)
Building wheels for collected packages: torch
  Building wheel for torch (setup.py): started
  Building wheel for torch (setup.py): finished with status 'error'
  Running setup.py clean for torch
Failed to build torch
Installing collected packages: torch, pgmpy
    Running setup.py install for torch: started
    Running setup.py install for torch: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.
WARNING: The candidate selected for download or install is a yanked version: 'torch' candidate (version 0.1.2.post2 at https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz#sha256=a43e37f8f927c5b18f80cd163daaf6a1920edafcab5102e02e3e14bb97d9c874 (from https://pypi.org/simple/torch/))
Reason for being yanked: 0.1.2 is past it's support date and confuses users on unsupported platforms
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\smith_5\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-23avsjzf\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-23avsjzf\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\smith_5\AppData\Local\Temp\pip-wheel-yml_6lmn'
       cwd: C:\Users\smith_5\AppData\Local\Temp\pip-install-23avsjzf\torch\
  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\smith_5\AppData\Local\Temp\pip-install-23avsjzf\torch\setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "C:\Users\smith_5\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\smith_5\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\smith_5\anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\smith_5\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\smith_5\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Users\smith_5\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\smith_5\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\smith_5\anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\smith_5\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\smith_5\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\smith_5\AppData\Local\Temp\pip-install-23avsjzf\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\smith_5\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-23avsjzf\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-23avsjzf\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\smith_5\AppData\Local\Temp\pip-install-23avsjzf\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\smith_5\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-23avsjzf\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-23avsjzf\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\smith_5\AppData\Local\Temp\pip-record-fz5qsm5e\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\smith_5\anaconda3\Include\torch'
         cwd: C:\Users\smith_5\AppData\Local\Temp\pip-install-23avsjzf\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\smith_5\AppData\Local\Temp\pip-install-23avsjzf\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "C:\Users\smith_5\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\smith_5\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\smith_5\anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\smith_5\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\smith_5\AppData\Local\Temp\pip-install-23avsjzf\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\smith_5\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\smith_5\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\smith_5\AppData\Local\Temp\pip-install-23avsjzf\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\smith_5\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-23avsjzf\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\smith_5\\AppData\\Local\\Temp\\pip-install-23avsjzf\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\smith_5\AppData\Local\Temp\pip-record-fz5qsm5e\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\smith_5\anaconda3\Include\torch' Check the logs for full command output.
```

The error print out to: conda install -c ankurankan pgmpy

```
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

Note: you may need to restart the kernel to use updated packages.

Building graph of deps:   0%|          | 0/4 [00:00<?, ?it/s]
Examining pgmpy:   0%|          | 0/4 [00:00<?, ?it/s]       
Examining @/win-32::__win==0=0:  25%|##5       | 1/4 [00:00<00:02,  1.27it/s]
Examining @/win-32::__win==0=0:  50%|#####     | 2/4 [00:00<00:00,  2.54it/s]
Examining @/win-32::__archspec==1=x86:  50%|#####     | 2/4 [00:00<00:00,  2.54it/s]
Examining python=3.8:  75%|#######5  | 3/4 [00:00<00:00,  2.54it/s]                 
                                                                   

Determining conflicts:   0%|          | 0/4 [00:00<?, ?it/s]
Examining conflict for pgmpy python:   0%|          | 0/4 [00:00<?, ?it/s]
                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by ankurankan** [comment]
@smithsophia1688 Seems like your pytorch installation is failing in the first case. And you have dependency problems when using conda. Some possible solutions:
1. Try installing with pip without using cache: `pip install pgmpy --no-cache-dir`
2. Create a new conda env and install into it. Something like:
```
conda create -n pgmpy python=3.8
conda activate pgmpy
conda install -c ankurankan pgmpy
```

**Comment by lqhuang** [comment]
Hey, @ankurankan I saw this issue is closed. But `torch` seems still existing as must-required dependency.

I wonder could I make a PR to make torch as optional dep like

```
pip install pgmpy[torch]
```

Furthermore, I want to contribute some lightweight optimizer instead of `pytorch`, because `torch` is really too large to install (~700MB).

How do you think about this.

**Comment by ankurankan** [comment]
@lqhuang Thanks for the suggestions. Yeah, I think it should be fine to move pytorch to optional dependencies. But for that, I would just move it from `requirements/runtime.txt` to `requirements/optional.txt`. Yes, I think it would also be great if we could replace pytorch with a light weight optimizer.
