### ISSUE TITLE
Dimensionality error when initializing DynamicBayesianNetwork

### ISSUE THREAD

**Issue by roy651** [pgmpy/pgmpy#1415]
### Subject of the issue
Dimensionality error when initializing DynamicBayesianNetwork

### Your environment
* pgmpy_1617178903326
* Python 3.8.2
* Operating System OS X 11.3.1

### Steps to reproduce
```
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import DBNInference

cancer_model = DBN()
cancer_model.add_edges_from([(('Pollution', 0), ('Cancer', 0)),
                      (('Smoker', 0), ('Cancer', 0)),
                      (('Cancer', 0), ('Xray', 0)),
                      (('Cancer', 0), ('Dyspnoea', 0))])

cpd_poll = TabularCPD(variable=('Pollution', 0), variable_card=2,
                      values=[[0.9], [0.1]])
cpd_smoke = TabularCPD(variable=('Smoker', 0), variable_card=2,
                       values=[[0.3], [0.7]])
cpd_cancer = TabularCPD(variable=('Cancer', 0), variable_card=2,
                        values=[[0.03, 0.05, 0.001, 0.02],
                                [0.97, 0.95, 0.999, 0.98]],
                        evidence=[('Smoker', 0), ('Pollution', 0)],
                        evidence_card=[2, 2])
cpd_xray = TabularCPD(variable=('Xray', 0), variable_card=2,
                      values=[[0.9, 0.2], [0.1, 0.8]],
                      evidence=[('Cancer', 0)], evidence_card=[2])
cpd_dysp = TabularCPD(variable=('Dyspnoea', 0), variable_card=2,
                      values=[[0.65, 0.3], [0.35, 0.7]],
                      evidence=[('Cancer', 0)], evidence_card=[2])


# Associating the parameters with the model structure.
cancer_model.add_cpds(cpd_poll, cpd_smoke, cpd_cancer, cpd_xray, cpd_dysp)

cancer_model.initialize_initial_state()
dbn_inf = DBNInference(cancer_model)
print(dbn_inf.query([('Xray', 0)], {('Smoker', 0): 0})[('Xray', 0)].values)
```

### Expected behaviour
```
Eliminating: ('Cancer', 0): 100%|██████████████████████████████████████████| 2/2 [00:00<00:00, 590.46it/s]
Eliminating: ('Cancer', 0): 100%|██████████████████████████████████████████| 2/2 [00:00<00:00, 651.69it/s]
[0.2224 0.7776]
```

### Actual behaviour
```
Traceback (most recent call last):
  File "test_dynamic_bayesian_network.py", line 69, in <module>
    cancer_model.initialize_initial_state()
  File "/Users/royabitbol/anaconda3/envs/dqf-new/lib/python3.8/site-packages/pgmpy/models/DynamicBayesianNetwork.py", line 570, in initialize_initial_state
    new_cpd = TabularCPD(
  File "/Users/royabitbol/anaconda3/envs/dqf-new/lib/python3.8/site-packages/pgmpy/factors/discrete/CPD.py", line 131, in __init__
    raise ValueError(
ValueError: values must be of shape (2, 1). Got shape: (1, 2)

```

**Comment by roy651** [comment]
Possible workaround in file: `pgmpy/models/DynamicBayesianNetwork.py` Line 573 - Change from:
```
                                np.reshape(cpd.values, (-1, 2)),
```
to:
```
                                np.reshape(cpd.values, (2, -1)),
```

**Comment by ankurankan** [comment]
@roy651 Thanks for the bug report. I think your suggested fix should work. I think this is happening because we changed the expected values shape in TabularCPD, but somehow missed changing it in this method. Would you like to open a PR fixing this and maybe also add some tests for this specific case?
