### ISSUE TITLE
Problem with DynamicBayesianNetwork for networks which span beyond 2 time generations

### ISSUE THREAD

**Issue by roy651** [pgmpy/pgmpy#1417]
### Subject of the issue
I may be wrong in my understanding but I assumed the DynamicBayesianNetwork supports multiple generations (>2) and I assumed the way to implement it is to define a network with time indexes larger than 1 (see code sample).
However, it seems like the code inside DynamicBayesianNetwork squashes any time index greater than 1 and reduces those time generations to 0 and 1.  Effectively, the nodes with time greater than 1 are eliminated from the graph and later while trying to add their CPDs the script fail for not finding their nodes.
Specifically the relevant code block is lines 175-180 inside function `add_edge`.

If there's another way (correct?) to achieve this, I'll be happy to know.

### Your environment
* pgmpy_1617178903326
* Python 3.8.2
* OS X 11.3.1

### Steps to reproduce
```
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import DBNInference

cancer_model = DBN()
cancer_model.add_edges_from([(('Pollution', 0), ('Cancer', 0)),
                      (('Smoker', 0), ('Cancer', 0)),
                      (('Cancer', 0), ('Xray', 0)),
                      (('Cancer', 0), ('Dyspnoea', 0)),
                      (('Pollution', 0), ('Pollution', 1)),
                      (('Smoker', 0), ('Smoker', 1)),
                      (('Pollution', 1), ('Cancer', 1)),
                      (('Smoker', 1), ('Cancer', 1)),
                      (('Cancer', 1), ('Xray', 1)),
                      (('Cancer', 1), ('Dyspnoea', 1)),
                      (('Pollution', 1), ('Pollution', 2)),
                      (('Smoker', 1), ('Smoker', 2)),
                      (('Pollution', 2), ('Cancer', 2)),
                      (('Smoker', 2), ('Cancer', 2)),
                      (('Cancer', 2), ('Xray', 2)),
                      (('Cancer', 2), ('Dyspnoea', 2))])

#########################    1     ######################
cpd_poll = TabularCPD(variable=('Pollution', 0), variable_card=2,
                      values=[[0.9], [0.1]])
cpd_smoke = TabularCPD(variable=('Smoker', 0), variable_card=2,
                       values=[[0.3], [0.7]])
cpd_cancer = TabularCPD(variable=('Cancer', 0), variable_card=2,
                        values=[[0.03, 0.05, 0.001, 0.02],
                                [0.97, 0.95, 0.999, 0.98]],
                        evidence=[('Smoker', 0), ('Pollution', 0)],
                        evidence_card=[2, 2])
cpd_xray = TabularCPD(variable=('Xray', 0), variable_card=2,
                      values=[[0.9, 0.2], [0.1, 0.8]],
                      evidence=[('Cancer', 0)], evidence_card=[2])
cpd_dysp = TabularCPD(variable=('Dyspnoea', 0), variable_card=2,
                      values=[[0.65, 0.3], [0.35, 0.7]],
                      evidence=[('Cancer', 0)], evidence_card=[2])

#########################    2     ######################
cpd_poll2 = TabularCPD(variable=('Pollution', 1), variable_card=2,
                      values=[[0.9, 0.1], [0.1, 0.9]],
                      evidence=[('Pollution', 0)], evidence_card=[2])
cpd_smoke2 = TabularCPD(variable=('Smoker', 1), variable_card=2,
                       values=[[0.7, 0.3], [0.3, 0.7]],
                       evidence=[('Smoker', 0)], evidence_card=[2])
cpd_cancer2 = TabularCPD(variable=('Cancer', 1), variable_card=2,
                        values=[[0.03, 0.05, 0.001, 0.02],
                                [0.97, 0.95, 0.999, 0.98]],
                        evidence=[('Smoker', 1), ('Pollution', 1)],
                        evidence_card=[2, 2])
cpd_xray2 = TabularCPD(variable=('Xray', 1), variable_card=2,
                      values=[[0.9, 0.2], [0.1, 0.8]],
                      evidence=[('Cancer', 1)], evidence_card=[2])
cpd_dysp2 = TabularCPD(variable=('Dyspnoea', 1), variable_card=2,
                      values=[[0.65, 0.3], [0.35, 0.7]],
                      evidence=[('Cancer', 1)], evidence_card=[2])

#########################    3     ######################
cpd_poll3 = TabularCPD(variable=('Pollution', 2), variable_card=2,
                       values=[[0.9, 0.1], [0.1, 0.9]],
                       evidence=[('Pollution', 1)], evidence_card=[2])
cpd_smoke3 = TabularCPD(variable=('Smoker', 2), variable_card=2,
                        values=[[0.7, 0.3], [0.3, 0.7]],
                        evidence=[('Smoker', 1)], evidence_card=[2])
cpd_cancer3 = TabularCPD(variable=('Cancer', 2), variable_card=2,
                         values=[[0.03, 0.05, 0.001, 0.02],
                                 [0.97, 0.95, 0.999, 0.98]],
                         evidence=[('Smoker', 2), ('Pollution', 2)],
                         evidence_card=[2, 2])
cpd_xray3 = TabularCPD(variable=('Xray', 2), variable_card=2,
                       values=[[0.9, 0.2], [0.1, 0.8]],
                       evidence=[('Cancer', 2)], evidence_card=[2])
cpd_dysp3 = TabularCPD(variable=('Dyspnoea', 2), variable_card=2,
                       values=[[0.65, 0.3], [0.35, 0.7]],
                       evidence=[('Cancer', 2)], evidence_card=[2])


# Associating the parameters with the model structure.
cancer_model.add_cpds(cpd_poll, cpd_smoke, cpd_cancer, cpd_xray, cpd_dysp,
                      cpd_poll2, cpd_smoke2, cpd_cancer2, cpd_xray2, cpd_dysp2,
                      cpd_poll3, cpd_smoke3, cpd_cancer3, cpd_xray3, cpd_dysp3)
```

### Expected behaviour
Script exits without any error

### Actual behaviour
```
Traceback (most recent call last):
  File "test_dynamic_bayesian_network_3_gen.py", line 80, in <module>
    cancer_model.add_cpds(cpd_poll, cpd_smoke, cpd_cancer, cpd_xray, cpd_dysp,
  File "/Users/royabitbol/anaconda3/envs/dqf-new/lib/python3.8/site-packages/pgmpy/models/DynamicBayesianNetwork.py", line 396, in add_cpds
    raise ValueError("CPD defined on variable not in the model", cpd)
ValueError: ('CPD defined on variable not in the model', <TabularCPD representing P(('Pollution', 2):2 | ('Pollution', 1):2) at 0x7fbfa88f5a30>)
```

**Comment by ankurankan** [comment]
@roy651 If I am understanding your example code correctly, it should be supported. Currently, we only have support for 2-TBNs (i.e. there shouldn't be any edge skipping a time-slice and the inter-time slice CPDs should be constant for all time points), which seems to be the case in your example. You are getting the error because you only need to specify the first two time slices, and then pgmpy should automatically create the rest. For your example, some thing like this should work:
```python
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import DBNInference

cancer_model = DBN()
cancer_model.add_edges_from([(('Pollution', 0), ('Cancer', 0)),
                      (('Smoker', 0), ('Cancer', 0)),
                      (('Cancer', 0), ('Xray', 0)),
                      (('Cancer', 0), ('Dyspnoea', 0)),
                      (('Pollution', 0), ('Pollution', 1)),
                      (('Smoker', 0), ('Smoker', 1)),
                      (('Pollution', 1), ('Cancer', 1)),
                      (('Smoker', 1), ('Cancer', 1)),
                      (('Cancer', 1), ('Xray', 1)),
                      (('Cancer', 1), ('Dyspnoea', 1))])

#########################    1     ######################
cpd_poll = TabularCPD(variable=('Pollution', 0), variable_card=2,
                      values=[[0.9], [0.1]])
cpd_smoke = TabularCPD(variable=('Smoker', 0), variable_card=2,
                       values=[[0.3], [0.7]])
cpd_cancer = TabularCPD(variable=('Cancer', 0), variable_card=2,
                        values=[[0.03, 0.05, 0.001, 0.02],
                                [0.97, 0.95, 0.999, 0.98]],
                        evidence=[('Smoker', 0), ('Pollution', 0)],
                        evidence_card=[2, 2])
cpd_xray = TabularCPD(variable=('Xray', 0), variable_card=2,
                      values=[[0.9, 0.2], [0.1, 0.8]],
                      evidence=[('Cancer', 0)], evidence_card=[2])
cpd_dysp = TabularCPD(variable=('Dyspnoea', 0), variable_card=2,
                      values=[[0.65, 0.3], [0.35, 0.7]],
                      evidence=[('Cancer', 0)], evidence_card=[2])

#########################    2     ######################
cpd_poll2 = TabularCPD(variable=('Pollution', 1), variable_card=2,
                      values=[[0.9, 0.1], [0.1, 0.9]],
                      evidence=[('Pollution', 0)], evidence_card=[2])
cpd_smoke2 = TabularCPD(variable=('Smoker', 1), variable_card=2,
                       values=[[0.7, 0.3], [0.3, 0.7]],
                       evidence=[('Smoker', 0)], evidence_card=[2])
cpd_cancer2 = TabularCPD(variable=('Cancer', 1), variable_card=2,
                        values=[[0.03, 0.05, 0.001, 0.02],
                                [0.97, 0.95, 0.999, 0.98]],
                        evidence=[('Smoker', 1), ('Pollution', 1)],
                        evidence_card=[2, 2])
cpd_xray2 = TabularCPD(variable=('Xray', 1), variable_card=2,
                      values=[[0.9, 0.2], [0.1, 0.8]],
                      evidence=[('Cancer', 1)], evidence_card=[2])
cpd_dysp2 = TabularCPD(variable=('Dyspnoea', 1), variable_card=2,
                      values=[[0.65, 0.3], [0.35, 0.7]],
                      evidence=[('Cancer', 1)], evidence_card=[2])

cancer_model.add_cpds(cpd_poll, cpd_smoke, cpd_cancer, cpd_xray, cpd_dysp,
                      cpd_poll2, cpd_smoke2, cpd_cancer2, cpd_xray2, cpd_dysp2)
```
And you can then query for other time points:
```
dbn_infer = DBNInference(cancer_model)
In [6]: dbn_infer.query([('Smoker', 3)])
Eliminating: ('Pollution', 1): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1034.86it/s]
Eliminating: ('Pollution', 1): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 974.29it/s]
Out[6]: 
{('Smoker',
  3): <DiscreteFactor representing phi(('Smoker', 3):2) at 0x7f301b47dbb0>}

In [7]: dbn_infer.query([('Smoker', 5)])
Eliminating: ('Pollution', 1): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 969.45it/s]
Eliminating: ('Pollution', 1): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1064.00it/s]
Out[7]: 
{('Smoker',
  5): <DiscreteFactor representing phi(('Smoker', 5):2) at 0x7f30673978b0>}

```

**Comment by roy651** [comment]
@ankurankan I understand now.
However, this raises a couple of other questions:
- Is it possible to model a kind of a root node - which is not replicated over the dynamic generations?
- Is it possible to model variable likelihood evidence - i.e. different probability tables on different layers?
- It might be an abuse of the model - but does it make sense to create a large dual-layer network covering all possible relations and then feed the evidence sparsely only on the relevant layer? Will the 32 node limit still be relevant for the single layer?

**Comment by ankurankan** [comment]
@roy651 

- Is it possible to model a kind of a root node - which is not replicated over the dynamic generations?

Yes, the current implementation does that. For specifying the model, we need to give all the values for the first two time slices. The first time slice is then considered constant (and it's CPDs), and the CPDs defining the inter timeslice edges (edges from time slice 0 to time slice 1) are then ones that get replicated for defining the future time slices. 

- Is it possible to model variable likelihood evidence - i.e. different probability tables on different layers?

No, currently it's not possible. But if the probability tables are different, you can also get the same model by specifying a full normal Bayesian Network. Though the inference might be computationally more expensive in that case but using something like VariableElimination with an efficient elimination order should be almost equivalent. 

- It might be an abuse of the model - but does it make sense to create a large dual-layer network covering all possible relations and then feed the evidence sparsely only on the relevant layer? Will the 32 node limit still be relevant for the single layer?

Yes, I think you might run into the 32 node limit problem in that case. The problem with very dense networks is that the intermediate distributions/tables get really large so might get to the 32 node limit, and also will require large amount of memory.
