### ISSUE TITLE
DynamicBayesianNetwork model function get_cdps does not gets all TabularCDPs

### ISSUE THREAD

**Issue by FelipeGiro** [pgmpy/pgmpy#1446]
### Subject of the issue

Apparently, the model `pgmpy.models.DynamicBayesianNetwork` function `get_cpds(*)` ignores all `TabularCDP` with time index 1, for example:

`cdp_T  = TabularCPD(('s', 1), 1000,  T.T, [('s', 0)], [1000])`

### Your environment
- pgmpy version: 0.1.15
- Python version: 3.7.10
- Operating: System Microsoft Windows 10 Pro

### Steps to Reproduce

Example from the code:

```
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD

dbn = DBN()
dbn.add_edges_from([(('D', 0),('G', 0)),(('I', 0),('G', 0)),(('D', 0),('D', 1)),(('I', 0),('I', 1))])
grade_cpd = TabularCPD(('G', 0), 3, [[0.3, 0.05, 0.9,  0.5],
                                     [0.4, 0.25, 0.08, 0.3],
                                     [0.3, 0.7,  0.02, 0.2]],
                       evidence=[('I', 0),('D', 0)],
                       evidence_card=[2, 2])
d_i_cpd = TabularCPD(('D',1), 2, [[0.6, 0.3],
                                  [0.4, 0.7]],
                     evidence=[('D',0)],
                     evidence_card=[2])
diff_cpd = TabularCPD(('D', 0), 2, [[0.6], [0.4]])
intel_cpd = TabularCPD(('I', 0), 2, [[0.7], [0.3]])
i_i_cpd = TabularCPD(('I', 1), 2, [[0.5, 0.4],
                                   [0.5, 0.6]],
                     evidence=[('I', 0)],
                     evidence_card=[2])
dbn.add_cpds(grade_cpd, d_i_cpd, diff_cpd, intel_cpd, i_i_cpd)
dbn.get_cpds()
```

### Expected behavior
```
[<TabularCPD representing P(('G', 0):3 | ('I', 0):2, ('D', 0):2) at 0x7ff7f27b0cf8>,
 <TabularCPD representing P(('D', 1):2 | ('D', 0):2) at 0x7ff810b9c2e8>, 
 <TabularCPD representing P(('D', 0):2) at 0x7ff7f27e6f98>,
 <TabularCPD representing P(('I', 0):2) at 0x7ff7f27e6ba8>,
 <TabularCPD representing P(('I', 1):2 | ('I', 0):2) at 0x7ff7f27e6668>]
```

### Actual behavior

```
[<TabularCPD representing P(('D', 0):2) at 0x21ee2840d48>,
 <TabularCPD representing P(('G', 0):3 | ('I', 0):2, ('D', 0):2) at 0x21ee2840848>,
 <TabularCPD representing P(('I', 0):2) at 0x21ee28400c8>]
```

Note all `TabularCPD representing P(('Something', 1):X ...)` is not included to the model. There is another example:

### Other example

```
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD

dbn = DBN([(('s', 0), ('s', 1)), (('s', 1), ('o', 1))])
# dbn.add_edges_from([(('s', 0), ('s', 1))])
cdp_s0 = TabularCPD(('s', 0), 2, [[0.2],[0.8]])
cdp_T  = TabularCPD(('s', 1), 2, [[0.5,0.3],[0.5,0.7]], [('s', 0)], [2])
cdp_o  = TabularCPD(('o', 1), 2, [[0.1,0.9],[0.9,0.1]], [('s', 1)], [2])
dbn.add_cpds(cdp_s0, cdp_T, cdp_o)
dbn.get_cpds()
```
It should:

```
[<TabularCPD representing P(('s', 0):2) at 0x246c03ccf08>,
 <TabularCPD representing P(('s', 1):2 | ('s', 0):2) at 0x246c02b7508>,
 <TabularCPD representing P(('o', 1):2 | ('s', 1):2) at 0x246c02b7808>]
```

But it gives:
```
[<TabularCPD representing P(('s', 0):2) at 0x246c02b8bc8>]
```

**Comment by FelipeGiro** [comment]
Just a note.

There is a TODO (line 488 in in `DynamicBayesianNetwork.py`) that indicating that the error in related to `get_cdps` only. But the error go further if you try to infer through DBN:

```
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference import DBNInference

dbn = DBN()
dbn.add_edges_from([(('D', 0),('G', 0)),(('I', 0),('G', 0)),(('D', 0),('D', 1)),(('I', 0),('I', 1))])
grade_cpd = TabularCPD(('G', 0), 3, [[0.3, 0.05, 0.9,  0.5],
                                     [0.4, 0.25, 0.08, 0.3],
                                     [0.3, 0.7,  0.02, 0.2]],
                       evidence=[('I', 0),('D', 0)],
                       evidence_card=[2, 2])
d_i_cpd = TabularCPD(('D',1), 2, [[0.6, 0.3],
                                  [0.4, 0.7]],
                     evidence=[('D',0)],
                     evidence_card=[2])
diff_cpd = TabularCPD(('D', 0), 2, [[0.6], [0.4]])
intel_cpd = TabularCPD(('I', 0), 2, [[0.7], [0.3]])
i_i_cpd = TabularCPD(('I', 1), 2, [[0.5, 0.4],
                                   [0.5, 0.6]],
                     evidence=[('I', 0)],
                     evidence_card=[2])
dbn.add_cpds(grade_cpd, d_i_cpd, diff_cpd, intel_cpd, i_i_cpd)
dbn.get_cpds()
dbn_inf = DBNInference(dbn)
```
The output is:

```
Traceback (most recent call last):

  File "C:\Developments\untitled2.py", line 31, in <module>
    dbn_inf = DBNInference(dbn)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pgmpy-0.1.15-py3.7.egg\pgmpy\inference\dbn_inference.py", line 75, in __init__
    self.one_and_half_junction_tree = one_and_half_markov_model.to_junction_tree()

  File "C:\ProgramData\Anaconda3\lib\site-packages\pgmpy-0.1.15-py3.7.egg\pgmpy\models\MarkovNetwork.py", line 496, in to_junction_tree
    self.check_model()

  File "C:\ProgramData\Anaconda3\lib\site-packages\pgmpy-0.1.15-py3.7.egg\pgmpy\models\MarkovNetwork.py", line 254, in check_model
    raise ValueError("Factors for all the variables not defined")

ValueError: Factors for all the variables not defined
```

**Comment by ankurankan** [comment]
@FelipeGiro I think this is happening because of the `time_slice` parameter in `get_cpds` method which is by default set to `0` and hence returns only the CPDs from 0th time slice. In the first example that you have mentioned:
```python
In [3]: dbn.get_cpds(time_slice=1)
Out[3]: 
[<TabularCPD representing P(('D', 1):2 | ('D', 0):2) at 0x7fb77429e670>,
 <TabularCPD representing P(('I', 1):2 | ('I', 0):2) at 0x7fb77429ed00>]

In [4]: dbn.get_cpds(time_slice=0)
Out[4]: 
[<TabularCPD representing P(('D', 0):2) at 0x7fb77429e730>,
 <TabularCPD representing P(('G', 0):3 | ('I', 0):2, ('D', 0):2) at 0x7fb77429e700>,
 <TabularCPD representing P(('I', 0):2) at 0x7fb77429ec40>]


```

**Comment by FelipeGiro** [comment]
Indeed, it is clearly documented.

Is there any interest to return all CPDs when no `time_slice` is inputted? Would it impact any dependencies? 

Another question: in `get_cpds` function, there is a `TODO: fix bugs in this` (line 488, `DynamicBayesianNetwork`). What are these bugs?

**Comment by ankurankan** [comment]
@FelipeGiro Yes, I think we should change the default behavior to return all CPDs. It will make it consistent with other get_cpds methods and is a bit confusing currently. I don't think it will impact anything else as long as it has the same behavior when time_slice is specified. 

I am sorry, I have no recollection of what that TODO is referring to. git blame does show that it was added by me though 😆
