### ISSUE TITLE
SIGKILL generated during VariableElimination query

### ISSUE THREAD

**Issue by rishubn** [pgmpy/pgmpy#1558]
### Subject of the issue
Hi,

I have a model with 250 binary value nodes. Most nodes are linked with deterministic functions and I am trying to do a query on 8 nodes to find their marginal PMF. When I run the query, after some time the program generates a SIGKILL itself and dies. Why is that? The memory usage of the program according to the system monitor tops out at 6GB. 

I should add: This issue only happens when I _add evidence_ to certain nodes. If I remove the evidence, the solver is able to find a solution in less then a second, so I really unsure of what's going on and how to find more information about the origin of the early termination

### Your environment
* pgmpy version = 0.1.19
* Python version = python 3.8.10
* Operating System Ubuntu 20.04 LTS

### Steps to reproduce
Can send code directly upon request - would not like to post it publicly 

### Expected behaviour
Successful inference

### Actual behaviour
SIGKILL

**Comment by ankurankan** [comment]
@rishubn I can't think of any reason why this might be happening. If you could share your code with me, I can try to reproduce and debug the issue?

**Comment by rishubn** [comment]
Do you have an email to which I can send it to?

**Comment by ankurankan** [comment]
@rishubn ankurankan@gmail.com

**Comment by ankurankan** [comment]
@rishubn Sorry for the late reply; it took me a while to figure out the problem. It seems that numpy has a limit of 26 variables for einsum operation, and in this case, intermediate computation requires more than 26 variables, hence the error. A possible solution (only if you have a machine with large memory) is to provide `elimination_order` to the query method. I would suggest trying out the different options: MinFill, MinWeight, MinNeighbors, WeightedMinFill, and see if any of them work, as using any of these elimination orders would avoid calls to einsum. Though the problem would still be that there would be some large intermediate arrays for which you need a machine with lots of memory. I have tried it with 32 gigs of RAM, and it fails.

**Comment by ankurankan** [comment]
@rishubn Using pytorch backend for einsum seems to work. I will have to think of a good way to integrate it into the main codebase but in the meanwhile you can use this branch: https://github.com/ankurankan/pgmpy/tree/issue/1558. If you have a GPU, you can also specify the device in this line: https://github.com/ankurankan/pgmpy/blob/issue/1558/pgmpy/inference/ExactInference.py#L369

**Comment by amajee11us** [comment]
I am getting this OOM error from my model. Is there a way to perform these operations using torch.einsum function rather than np.einsum ? Can you please suggest the modifications needed ?

Error I am receiving : 
[Modelling] Performing Variable Elimation on Markov Network ...
Eliminating: 101:   6%|█████▌                                                                                             | 69/1241 [00:34<09:51,  1.98it/s]
Traceback (most recent call last):
  File "/home/shared/anay/multiClassMarkovModel/main.py", line 63, in <module>
    y_pred = model.evaluate(X_test, Y_test)
  File "/home/shared/anay/multiClassMarkovModel/src/infer.py", line 48, in evaluate
    res_temp.append(self.__infer(
  File "/home/shared/anay/multiClassMarkovModel/src/infer.py", line 22, in __infer
    result = self.engine.query(
  File "/home/shared/anay/anaconda3/envs/nb/lib/python3.9/site-packages/pgmpy-0.1.19-py3.9.egg/pgmpy/inference/ExactInference.py", line 417, in query
  File "/home/shared/anay/anaconda3/envs/nb/lib/python3.9/site-packages/pgmpy-0.1.19-py3.9.egg/pgmpy/inference/ExactInference.py", line 205, in _variable_elimination
  File "/home/shared/anay/anaconda3/envs/nb/lib/python3.9/site-packages/pgmpy-0.1.19-py3.9.egg/pgmpy/factors/base.py", line 73, in factor_product
  File "/home/shared/anay/anaconda3/envs/nb/lib/python3.9/site-packages/pgmpy-0.1.19-py3.9.egg/pgmpy/factors/base.py", line 73, in <lambda>
  File "/home/shared/anay/anaconda3/envs/nb/lib/python3.9/site-packages/pgmpy-0.1.19-py3.9.egg/pgmpy/factors/discrete/DiscreteFactor.py", line 930, in __mul__
  File "/home/shared/anay/anaconda3/envs/nb/lib/python3.9/site-packages/pgmpy-0.1.19-py3.9.egg/pgmpy/factors/discrete/DiscreteFactor.py", line 704, in product
  File "<__array_function__ internals>", line 180, in einsum
  File "/home/shared/anay/anaconda3/envs/nb/lib/python3.9/site-packages/numpy/core/einsumfunc.py", line 1371, in einsum
    return c_einsum(*operands, **kwargs)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 16.0 GiB for an array with shape (2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2) and data type float64

**Comment by ankurankan** [comment]
@amajee11us I still haven't integrated the solution that I implemented in https://github.com/ankurankan/pgmpy/tree/issue/1558 in the main codebase, but you can still use that branch to use the pytorch backend for einsum. Or if you would like to implement it for the latest version, you can refer to the commit (https://github.com/ankurankan/pgmpy/commit/efad0e661cdc285b4217fe0c8a37700a698399b2).

**Comment by amajee11us** [comment]
@ankurankan thanks for your reply !! I understand that this integration is not yet done, but I took the liberty to dig a little deeper.
For smaller networks the numpy version works perfectly, but for networks like the ones I am working on has 1600 variables and each variable has multiple discrete states the dimensions of the matrix after factor_product function call is very large. 
The last snippet I posted it is clear that it has around 32 dimensions. The maximum number of dimensions that a numpy array can process is maxed at 32 and thus this line (https://github.com/pgmpy/pgmpy/blob/51fe08d9e05839b779a18e04f36f13814868b6f3/pgmpy/factors/discrete/DiscreteFactor.py#L704) throws an error.
I think moving to torch or some custom implementation would help in this case. Any suggestions to resolve this?

**Comment by ankurankan** [comment]
@amajee11us Sorry for the late reply, I was on vacation. Yes, numpy has both limits on the number of dimensions (32) and the max number of arguments it can process in an einsum call (26 if I remember correctly). Another thing to keep in mind is that factors with more than 32 variables are not very feasible computationally because the size of the values array with even 2 states per variable would be around 32 GBs (assuming float values), so any meaningful computation would run out of memory on most computers. I usually advise reducing the complexity of the model structure in such scenarios. 

I don't know if pytorch also has any of these limitations. But ideally, I would like to have an option for the user to specify a backend with the option of either numpy or pytorch. I would imagine that for smaller models the overhead of using a GPU would exceed the benefits but for large models, GPUs might be faster.
