### ISSUE TITLE
DBN Traceback Error Thrown

### ISSUE THREAD

**Issue by THEForgiven** [pgmpy/pgmpy#1596]
### Subject of the issue
I get the following error thrown after entering the three priors and I'm not sure why:
Traceback (most recent call last):
  File "/home/kylelitz/Documents/Odds.py", line 19, in <module>
    dbn.add_edge('DayPrior', 'TenMinutesPrior')
  File "/home/kylelitz/.local/lib/python3.10/site-packages/pgmpy/models/DynamicBayesianNetwork.py", line 241, in add_edge
    raise ValueError("Nodes must be of type (node, time_slice).")
ValueError: Nodes must be of type (node, time_slice).

My code is:

from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD

(Comment)Get the prior odds from the user
day_prior_odds = float(input("Enter the odds of the event at one day prior (0-1): "))
ten_minutes_prior_odds = float(input("Enter the odds of the event at 10 minutes prior (0-1): "))
three_minutes_prior_odds = float(input("Enter the odds of the event at 3 minutes prior (0-1): "))

(Comment)Create the DBN
dbn = DBN()

(Comment)Add the nodes for the odds at different time intervals
dbn.add_node('DayPrior')
dbn.add_node('TenMinutesPrior')
dbn.add_node('ThreeMinutesPrior')
dbn.add_node('StartTime')

(Comment)Add the edges between the nodes
dbn.add_edge('DayPrior', 'TenMinutesPrior')
dbn.add_edge('TenMinutesPrior', 'ThreeMinutesPrior')
dbn.add_edge('ThreeMinutesPrior', 'StartTime')

(Comment) Define the conditional probability distributions (CPDs) for each node
day_prior_cpd = TabularCPD('DayPrior', 2, [[day_prior_odds, 1-day_prior_odds]])
ten_minutes_prior_cpd = TabularCPD('TenMinutesPrior', 2, [[ten_minutes_prior_odds, 1-ten_minutes_prior_odds], [0.1, 0.9]], evidence=['DayPrior'], evidence_card=[2])
three_minutes_prior_cpd = TabularCPD('ThreeMinutesPrior', 2, [[three_minutes_prior_odds, 1-three_minutes_prior_odds], [0.3, 0.7]], evidence=['TenMinutesPrior'], evidence_card=[2])
start_time_cpd = TabularCPD('StartTime', 2, [[0.8, 0.2], [0.5, 0.5]], evidence=['ThreeMinutesPrior'], evidence_card=[2])

(Comment) Add the CPDs to the DBN
dbn.add_cpds(day_prior_cpd, ten_minutes_prior_cpd, three_minutes_prior_cpd, start_time_cpd)

(Comment) Check if the DBN is consistent
dbn.check_model()

(Comment) Set the evidence for the odds at one day prior, 10 minutes prior, and 3 minutes prior
evidence = {'DayPrior': day_prior_odds > 0.5, 'TenMinutesPrior': ten_minutes_prior_odds > 0.5, 'ThreeMinutesPrior': three_minutes_prior_odds > 0.5}

(Comment) Infer the odds of the event at the start time
start_time_odds = dbn.predict_probability(['StartTime'], evidence=evidence)

(Comment) Print the inferred odds
print(start_time_odds)

### Your environment
* pgmpy version 0.1.21
* Python version 3.10.6
* Operating System: NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

### Steps to reproduce
Copy the above code and run it.  It should ask for decimal odds at the day prior, at 10 minutes prior, and at 3 minutes prior to the start.  The goal is to use DBN to estimate the odds at the start time 0.

### Expected behaviour
 It should ask for decimal odds at the day prior, at 10 minutes prior, and at 3 minutes prior to the start.  The goal is to use DBN to estimate the odds at the start time 0.

### Actual behaviour
The cited Traceback error above is thrown and I'm not sure why.

**Comment by ankurankan** [comment]
@THEForgiven I think in this example, you can simply use BayesianNetwork instead of DBN. The DBN implementation in pgmpy expects a repeating structure over time (the structure and CPDs remain constant), and you define it by defining just the repeating part of the network (2-TBN). In this case, as your CPDs are different for each node, we can't define it as a repeating structure. And given your inference query, I think using BayesianNetwork would give you the correct answer.

**Comment by THEForgiven** [comment]
Thanks! 
-------- Original message --------From: Ankur Ankan ***@***.***> Date: 1/17/23  2:28 AM  (GMT-05:00) To: pgmpy/pgmpy ***@***.***> Cc: THEForgiven ***@***.***>, Mention ***@***.***> Subject: Re: [pgmpy/pgmpy] DBN Traceback Error Thrown (Issue #1596) 
@THEForgiven I think in this example, you can simply use BayesianNetwork instead of DBN. The DBN implementation in pgmpy expects a repeating structure over time (the structure and CPDs remain constant), and you define it by defining just the repeating part of the network (2-TBN). In this case, as your CPDs are different for each node, we can't define it as a repeating structure. And given your inference query, I think using BayesianNetwork would give you the correct answer.
