### ISSUE TITLE
missing dependency in conda meta.yaml

### ISSUE THREAD

**Issue by stessaris** [pgmpy/pgmpy#1607]
### Subject of the issue

The conda `meta.yaml` is missing the `opt_einsum` dependency so the published package doesn't install it. The solution is to add the package among the `run` requirements.

BTW there's a reason why the versions of the required packages in `mata.yaml` are not constrained as in `requirements.txt`? 

### Your environment
* pgmpy 0.1.21
* Python 3.10 (irrelevant)
* Operating System OSX (irrelevant)

### Steps to reproduce

The following commands create a new conda environment with `pgmpy` (I'm using `micromamba` for efficiency, but using `conda` you get the same results):

```bash
$ micromamba env create -n pgmpy
$ micromamba activate pgmpy
$ micromamba install -c ankurankan pgmpy
$ micromamba list|grep pgmpy
List of packages in environment: "/Users/xxxx/micromamba/envs/pgmpy"
  pgmpy               0.1.21     py310_0              ankurankan
$ micromamba list|grep opt_einsum
$ python -c "from pgmpy.models import BayesianNetwork"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxxx/micromamba/envs/pgmpy/lib/python3.10/site-packages/pgmpy/models/__init__.py", line 1, in <module>
    from .BayesianNetwork import BayesianNetwork
  File "/Users/xxxx/micromamba/envs/pgmpy/lib/python3.10/site-packages/pgmpy/models/BayesianNetwork.py", line 16, in <module>
    from pgmpy.factors.continuous import ContinuousFactor
  File "/Users/xxxx/micromamba/envs/pgmpy/lib/python3.10/site-packages/pgmpy/factors/__init__.py", line 1, in <module>
    from .base import factor_divide, factor_product, factor_sum_product
  File "/Users/xxxx/micromamba/envs/pgmpy/lib/python3.10/site-packages/pgmpy/factors/base.py", line 5, in <module>
    from opt_einsum import contract
ModuleNotFoundError: No module named 'opt_einsum'
$ micromamba install opt_einsum
$ micromamba list|grep opt_einsum
  opt_einsum          3.3.0      pyhd8ed1ab_1         conda-forge
$ python -c "from pgmpy.models import BayesianNetwork"
$
```

### Expected behaviour

Python import of `pgmpy` should succeed

### Actual behaviour

Python import of `pgmpy` raises a `ModuleNotFoundError`

**Comment by ankurankan** [comment]
@stessaris Thanks for reporting this. I have added opt_einsum in the dependencies now. And the reason behind not constraining the versions in conda is that as conda packages usually lag behind pip, and I didn't have a good way to have them always match. Please let me know if you know of any ways around this or have any suggestions on dealing with it.

**Comment by stessaris** [comment]
Regarding constraining the version of dependencies, since I noticed that they're all in the form `>=` I assumed that pgmpy might have problems with earlier versions of some of the packages. The conda solver might install an incompatible version of some packages because of some other requirements of the environment.

I guess you can specify constraints in the form ">= earlier working version, <= latest working version", in this way you're sure the solver won't install incompatible packages and will use the most recent among the compatible ones.

BTW the <= constraint would be useful also for the Pip package because it'd prevent that an API change in some of the packages will break your code (I've been bitten by this in the past)
