### ISSUE TITLE
DBN inference: unexpected results

### ISSUE THREAD

**Issue by laikoni** [pgmpy/pgmpy#1638]
### Subject of the issue
I am aware that currently there are some problems with DBN inference, causing it to fail with an error (https://github.com/pgmpy/pgmpy/issues/1585, https://github.com/pgmpy/pgmpy/issues/1583). I experienced the same for most DBNs I tried, however for some others the inference seemingly goes through and returns results, though not the results I expected.

Below is a minimal working example with a small DBN, as well as an equivalent BN with the same structure as the DBN unfolded to depth 1. The query is a simple forward query at time 1 given evidence at time 0. 

In my understanding, both should return the same values, however the output differs significantly. The result of the BN inference is in line with what I expected from manual computation.

### Your environment
* pgmpy version: 0.1.22 (dev branch)
* Python version: 3.11.0
* Operating System: macOS 13.2.1 

### Steps to reproduce
```python
from pgmpy.models import BayesianNetwork, DynamicBayesianNetwork
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference.dbn_inference import DBNInference
from pgmpy.inference import BeliefPropagation

# DBN
dbn = DynamicBayesianNetwork()
dbn.add_edges_from([
    (('A', 0), ('A', 1)), 
    (('A', 0), ('B', 0)), 
    (('A', 1), ('B', 1)), 
    (('B', 0), ('B', 1))])
cpt_A0 = TabularCPD(('A', 0), 2, [[0.5], [0.5]])
cpt_B0 = TabularCPD(('B', 0), 2, [[0.25, 0.75], [0.75, 0.25]],
                    evidence=[('A', 0)], evidence_card=[2])
cpt_A1 = TabularCPD(('A', 1), 2, [[0.8, 0.1],[0.2, 0.9]],
                    evidence=[('A', 0)], evidence_card=[2])
cpt_B1 = TabularCPD(('B', 1), 2, [[0.5, 0.6, 0.2, 0.4], [0.5, 0.4, 0.8, 0.6]],
                    evidence=[('A', 1), ('B', 0)],evidence_card=[2, 2])
dbn.add_cpds(cpt_A0, cpt_B0, cpt_A1, cpt_B1)
dbn.initialize_initial_state()

dbn_inf = DBNInference(dbn)
result = dbn_inf.query([('B', 1)], {('B', 0):0})
if result:
    print(result[('B', 1)])

# Equivalent BN
bn = BayesianNetwork()
bn.add_edges_from([
    ('A0', 'A1'), 
    ('A0', 'B0'), 
    ('A1', 'B1'), 
    ('B0', 'B1')])
cpt_A0 = TabularCPD('A0', 2, [[0.5], [0.5]])
cpt_B0 = TabularCPD('B0', 2, [[0.25, 0.75], [0.75, 0.25]],
                    evidence=['A0'], evidence_card=[2])
cpt_A1 = TabularCPD('A1', 2, [[0.8, 0.1],[0.2, 0.9]],
                    evidence=['A0'], evidence_card=[2])
cpt_B1 = TabularCPD('B1', 2, [[0.5, 0.6, 0.2, 0.4], [0.5, 0.4, 0.8, 0.6]],
                    evidence=['A1', 'B0'],evidence_card=[2, 2])
bn.add_cpds(cpt_A0, cpt_B0, cpt_A1, cpt_B1)

bp = BeliefPropagation(bn)
result = bp.query(['B1'], {'B0':0})
print(result)
```

### Expected behaviour
Both queries should return the same values.

### Actual behaviour
```
+-------------+-----------------+
| ('B', 1)    |   phi(('B', 1)) |
+=============+=================+
| ('B', 1)(0) |          0.3688 |
+-------------+-----------------+
| ('B', 1)(1) |          0.6312 |
+-------------+-----------------+
+-------+-----------+
| B1    |   phi(B1) |
+=======+===========+
| B1(0) |    0.2825 |
+-------+-----------+
| B1(1) |    0.7175 |
+-------+-----------+
```

**Comment by ankurankan** [comment]
@laikoni Thanks for reporting this. This indeed seems like a bug. I will try to fix it but in the meanwhile, you can also use approx inference for DBNs which seems to give the correct result.
```python
In [11]:  from pgmpy.inference import ApproxInference

In [12]: infer = ApproxInference(dbn)

In [13]: infer.query([('B', 1)], evidence={('B', 0): 0})
  0%|                                                                                                                                                   | 0/4 [00:00<?, ?it/s]
Out[13]: <DiscreteFactor representing phi(('B', 1):2) at 0x7f7b350aaa40>

In [14]: print(_)
+-------------+-----------------+
| ('B', 1)    |   phi(('B', 1)) |
+=============+=================+
| ('B', 1)(0) |          0.2847 |
+-------------+-----------------+
| ('B', 1)(1) |          0.7153 |
+-------------+-----------------+
```

**Comment by laikoni** [comment]
Thanks for the pointer to approximate inference. For the present example, it indeed works as expected. However, as soon as I query for a variable at a time greater than 1, I get key error. E.g., for `infer.query([('B', 2)], evidence={('B', 0): 0})`:

```python
Traceback (most recent call last):
  File "/Users/###/Documents/cybn-dev/pgmpy_bug_approxinf.py", line 32, in <module>
    result = infer.query([('B', 2)], evidence={('B', 0): 0})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/###/Library/Caches/pypoetry/virtualenvs/cybn-fkLsveqZ-py3.11/lib/python3.11/site-packages/pgmpy/inference/ApproxInference.py", line 131, in query
    return self.get_distribution(samples, variables=variables, joint=joint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/###/Library/Caches/pypoetry/virtualenvs/cybn-fkLsveqZ-py3.11/lib/python3.11/site-packages/pgmpy/inference/ApproxInference.py", line 61, in get_distribution
    samples.groupby(variables).size() / samples.shape[0]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/###/Library/Caches/pypoetry/virtualenvs/cybn-fkLsveqZ-py3.11/lib/python3.11/site-packages/pandas/core/frame.py", line 8262, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/Users/###/Library/Caches/pypoetry/virtualenvs/cybn-fkLsveqZ-py3.11/lib/python3.11/site-packages/pandas/core/groupby/groupby.py", line 931, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/Users/###/Library/Caches/pypoetry/virtualenvs/cybn-fkLsveqZ-py3.11/lib/python3.11/site-packages/pandas/core/groupby/grouper.py", line 985, in get_grouper
    raise KeyError(gpr)
KeyError: ('B', 2)
```
Am I missing something here?

**Comment by ankurankan** [comment]
@laikoni Sorry, I forgot to mention that this was recently fixed and is not released yet. If you install pgmpy from the dev branch on GitHub, it should work fine.
```
pip install git+https://github.com/pgmpy/pgmpy.git@dev
```

**Comment by Mudassiruddin7** [comment]
traced this through, _get_evidence() has an implicit return None when evidence_dict is falsy. whoever calls it and does .update() on the result then gets AttributeError: 'NoneType' has no attribute 'update'. tbh surprised this wasn't caught earlier, it's a pretty fundamental missing return. fixing in a PR that also adds a regression test for the empty evidence case

**Comment by DARHWOLF** [comment]
Can this issue be closed if it has been fixed @ankurankan @laikoni ?

**Comment by laikoni** [comment]
I updated to the last version on the dev branch and ran the above code again (changing `BayesianNetwork` to `DiscreteBayesianNetwork`). Except for a warning that is now thrown by `dbn_inf = DBNInference(dbn)` for some reason, the output is still the same for me:

```
WARNING:pgmpy:Replacing existing CPD for ('A', 1)
WARNING:pgmpy:Replacing existing CPD for ('B', 1)
+-------------+-----------------+
| ('B', 1)    |   phi(('B', 1)) |
+=============+=================+
| ('B', 1)(0) |          0.3688 |
+-------------+-----------------+
| ('B', 1)(1) |          0.6313 |
+-------------+-----------------+
+-------+-----------+
| B1    |   phi(B1) |
+=======+===========+
| B1(0) |    0.2825 |
+-------+-----------+
| B1(1) |    0.7175 |
+-------+-----------+
```

So, no, it looks like the fix did not resolve the reported issue.
