### ISSUE TITLE
when getting example model, errors happened

### ISSUE THREAD

**Issue by zqxyus** [pgmpy/pgmpy#1703]
### Subject of the issue
Traceback (most recent call last):
  File "D:\E-BOOK\temp\bayes\code\test.py", line 4, in <module>
    get_example_model(model='earthquake')
  File "C:\python\lib\site-packages\pgmpy\utils\utils.py", line 113, in get_example_model
    reader = BIFReader(string=content.decode("utf-8"), n_jobs=1)
  File "C:\python\lib\site-packages\pgmpy\readwrite\BIF.py", line 95, in __init__
    ) = self.get_variable_grammar()
  File "C:\python\lib\site-packages\pgmpy\readwrite\BIF.py", line 111, in get_variable_grammar
    word_expr = Word(pp.unicode.alphanums + "_" + "-")
AttributeError: type object 'str' has no attribute 'alphanums

### Your environment
* pgmpy 0.1.24
* Python 3.91

### Steps to reproduce
```
from pgmpy.utils import get_example_model
from pgmpy.sampling import BayesianModelSampling
get_example_model(model='earthquake')
```

**Comment by ankurankan** [comment]
@xy-whu Interesting, this seems to work fine for me:
```python
In [2]: from pgmpy.utils import get_example_model

In [3]: get_example_model(model='earthquake')
Out[3]: <pgmpy.models.BayesianNetwork.BayesianNetwork at 0x7f6c395b3820>
```

Could you maybe try updating all the dependencies (might be because of an older version of pyparsing) ?
