### ISSUE TITLE
Key Error in MPLP Inference over Markov Network

### ISSUE THREAD

**Issue by superctj** [pgmpy/pgmpy#1738]
### Subject of the issue
Hi, thank you for open-sourcing this great library, which is very valuable to my project! I was running MPLP approximate inference for a Markov Network and had a key error. My Markov network consists of unary factors (factors over single nodes) and ternary factors (factors over a clique of three nodes). I found the problem is caused by the default setting of tighten_triplet=True in the map_query method. If I set it to False then the algorithm runs to complete.

### Your environment
* pgmpy version: 0.1.24
* Python version: 3.10.13
* Operating System: Linux

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a **minimal reproducible code** of
the issue you are facing if possible.

```python
from itertools import combinations

from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import Mplp
from pgmpy.models import MarkovNetwork

UNARY_TABLE = [0.5, 0.5]
TERNARY_TABLE = [1, 1, 1, 0, 1, 0, 0, 1]


def test_mplp_inference():
    mrf = MarkovNetwork()

    # Add variables and unary factors
    variable_names = ["R_1-2", "R_1-3", "R_1-4", "R_2-3", "R_2-4", "R_3-4"]

    for var_name in variable_names:
        mrf.add_node(var_name)

        unary_factor = DiscreteFactor(
            [var_name], cardinality=[2], values=UNARY_TABLE
        )
        mrf.add_factors(unary_factor)

    # Add ternary factors
    ternary_combos = combinations(range(1, 5), 3)

    for combo in ternary_combos:
        var1 = f"R_{combo[0]}-{combo[1]}"
        var2 = f"R_{combo[0]}-{combo[2]}"
        var3 = f"R_{combo[1]}-{combo[2]}"

        mrf.add_edges_from([(var1, var2), (var1, var3), (var2, var3)])
        ternary_factor = DiscreteFactor(
            [var1, var2, var3], cardinality=[2, 2, 2], values=TERNARY_TABLE
        )
        ternary_factor.normalize()

        mrf.add_factors(ternary_factor)

    mplp = Mplp(mrf)
    results = mplp.map_query()
    print(results)    
```

### Expected behaviour
No error.

### Actual behavior
Traceback (most recent call last):
  File "/home/congtj/openforge/openforge/mrf_inference_mplp.py", line 164, in <module>
    results = mplp.map_query(tighten_triplet=True)
  File "/home/congtj/miniconda3/envs/openforge/lib/python3.10/site-packages/pgmpy/inference/mplp.py", line 580, in map_query
    self._tighten_triplet(max_iterations, later_iter, max_triplets, prolong)
  File "/home/congtj/miniconda3/envs/openforge/lib/python3.10/site-packages/pgmpy/inference/mplp.py", line 446, in _tighten_triplet
    triplet_scores = self._get_triplet_scores(triangles)
  File "/home/congtj/miniconda3/envs/openforge/lib/python3.10/site-packages/pgmpy/inference/mplp.py", line 383, in _get_triplet_scores
    [
  File "/home/congtj/miniconda3/envs/openforge/lib/python3.10/site-packages/pgmpy/inference/mplp.py", line 384, in <listcomp>
    np.amax(self.objective[frozenset(intersect)].values)
KeyError: frozenset({'R_2-14', 'R_10-14'})

I was also wondering if it is possible to plug in evidence to MPLP inference like in query method of Belief Propagation. Thanks!

**Comment by ankurankan** [comment]
@superctj Thanks for reporting the issue. I had a quick look at it but I am unsure what is causing this. I will try to dig deeper and update here.

**Comment by KapilSareen** [comment]
Hello @ankurankan @superctj, I was looking into this issue and seems like your script was missing binary factors, that's why the issue was arising [here](https://github.com/pgmpy/pgmpy/blob/dev/pgmpy/inference/mplp.py#L377-L387), where binary combinations are being checked.

I played around with your script and added binary factors, and got it working without any error:

```python
from itertools import combinations

from pgmpy.factors.discrete import DiscreteFactor
from pgmpy.inference import Mplp
from pgmpy.models import DiscreteMarkovNetwork

UNARY_TABLE = [0.5, 0.5]
TERNARY_TABLE = [1, 1, 1, 0, 1, 0, 0, 1]
BINARY_TABLE = [0.5, 0.5, 0.5, 0.5]

def test_mplp_inference():
    mrf = DiscreteMarkovNetwork()

    # Add variables and unary factors
    variable_names = ["R_1-2", "R_1-3", "R_1-4", "R_2-3", "R_2-4", "R_3-4"]

    for var_name in variable_names:
        mrf.add_node(var_name)

        unary_factor = DiscreteFactor(
            [var_name], cardinality=[2], values=UNARY_TABLE
        )
        mrf.add_factors(unary_factor)

    # Add ternary factors
    ternary_combos = combinations(range(1, 5), 3)
    
    for combo in ternary_combos:
        var1 = f"R_{combo[0]}-{combo[1]}"
        var2 = f"R_{combo[0]}-{combo[2]}"
        var3 = f"R_{combo[1]}-{combo[2]}"

        mrf.add_edges_from([(var1, var2), (var1, var3), (var2, var3)])
        ternary_factor = DiscreteFactor(
            [var1, var2, var3], cardinality=[2, 2, 2], values=TERNARY_TABLE
        )
        ternary_factor.normalize()

        mrf.add_factors(ternary_factor)


    # Add binary factors
    binary_combos = combinations(variable_names, 2)

    for combo in binary_combos:
        var1 = combo[0]
        var2 = combo[1]
        mrf.add_edges_from([(var1, var2)])
        binary_factors = DiscreteFactor(
            [var1, var2], cardinality=[2, 2], values=BINARY_TABLE
        )
        binary_factors.normalize()

        mrf.add_factors

    mplp = Mplp(mrf)
    results = mplp.map_query()
    print(results)    

if __name__ == "__main__":
    test_mplp_inference()
    print("Test completed successfully!")
```

Here's the output for reference:
```
{'R_1-2': np.int64(0), 'R_1-3': np.int64(0), 'R_1-4': np.int64(0), 'R_2-3': np.int64(0), 'R_2-4': np.int64(0), 'R_3-4': np.int64(0)}
Test completed successfully!
```

Could you please confirm if I overlooked anything?

**Comment by tanay-man** [comment]
You are right @KapilSareen. Imo instead of a workaround, a check should be added to throw an error.
