### ISSUE TITLE
ApproxInference.query() Traceback

### ISSUE THREAD

**Issue by RemainC** [pgmpy/pgmpy#1793]
### Subject of the issue
I'm trying to use ApproxInference to query the solution of DBN, but traceback happened. 
Even though I used the example given in ApproxInference.py(Line 135), it still reported an error.

### Your environment
* pgmpy version 0.1.25
* Python version 3.9.13
* Operating System Windows 11

### Steps to reproduce
```Python
from pgmpy.utils import get_example_model
from pgmpy.inference import ApproxInference
model = get_example_model("alarm")
infer = ApproxInference(model)
infer.query(["HISTORY"])
```

### Actual behaviour
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\PyProject\DBN3_9\.venv\lib\site-packages\pgmpy\inference\ApproxInference.py", line 151, in query
    samples = self.model.simulate(
  File "D:\PyProject\DBN3_9\.venv\lib\site-packages\pgmpy\models\BayesianNetwork.py", line 1301, in simulate
    samples = BayesianModelSampling(model).forward_sample(
  File "D:\PyProject\DBN3_9\.venv\lib\site-packages\pgmpy\sampling\Sampling.py", line 125, in forward_sample
    sampled[node] = sample_discrete_maps(
  File "D:\PyProject\DBN3_9\.venv\lib\site-packages\pgmpy\utils\mathext.py", line 194, in sample_discrete_maps
    samples[(weight_indices == weight_index)] = np.random.choice(
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed
```

**Comment by ankurankan** [comment]
@RemainC Do you have numpy 2.x installed by any chance? Numpy 2.x introduced some breaking changes, and I suspect you are getting the error because of that. We are still working on supporting it: https://github.com/pgmpy/pgmpy/pull/1780. In the meanwhile, if you downgrade your numpy version, the code above should work.

**Comment by RemainC** [comment]
Thank you for your reply. I have installed numpy 1.26.0 instead of 2.0, it works.
