### ISSUE TITLE
Bug in Variable Elimination query

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#261]
``` python
from pgmpy.inference import VariableElimination
from pgmpy.models import BayesianModel
import numpy as np
import pandas as pd
values = pd.DataFrame(np.random.randint(low=0, high=2, size=(1000, 5)),
                      columns=['A', 'B', 'C', 'D', 'E'])
model = BayesianModel([('A', 'B'), ('C', 'B'), ('C', 'D'), ('B', 'E')])
model.fit(values)
inference = VariableElimination(model)


inference.query(['A', 'B'])
Out[9]: {'B': <pgmpy.factors.Factor.Factor object at 0x7f7590692c88>, 'A': <pgmpy.factors.Factor.Factor object at 0x7f7590692c18>}

inference.query(['A', 'B']).values()
Traceback (most recent call last):

  File "<ipython-input-10-d9839ce95eb6>", line 1, in <module>
    inference.query(['A', 'B']).values()

  File "/home/ankur/pgmpy/pgmpy/inference/ExactInference.py", line 56, in query
    phi.marginalize(var)

  File "/home/ankur/pgmpy/pgmpy/factors/Factor.py", line 188, in marginalize
    raise Exceptions.ScopeError("%s not in scope" % variable)

ScopeError: 'E not in scope'
```

**Comment by ankurankan** [comment]
The problem is that the original `self.factors` is getting modified when Variable Elimination is run. Using `deepcopy` resolves this issue.
