### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#262]
``` python
model = BayesianModel([('A', 'B'), ('B', 'C'), ('C', 'D'), ('D', 'A')])
Traceback (most recent call last):

  File "<ipython-input-33-cd7b400080b4>", line 1, in <module>
    model = BayesianModel([('A', 'B'), ('B', 'C'), ('C', 'D'), ('D', 'A')])

  File "/home/ankur/pgmpy/pgmpy/models/BayesianModel.py", line 80, in __init__
    self.add_edges_from(ebunch)

  File "/home/ankur/pgmpy/pgmpy/base/DirectedGraph.py", line 149, in add_edges_from
    self.add_edge(*edge, **kwargs)

  File "/home/ankur/pgmpy/pgmpy/models/BayesianModel.py", line 111, in add_edge
    'Loops are not allowed. (%s->%s) is already present.' % (v, u))

ValueError: Loops are not allowed. (A->D) is already present.
```

Shows `(A -> D)` is already present but is not.

**Comment by palashahuja** [comment]
It is clearly straightforward that by joining the last edge, a loop is formed. This case is not included in the above error . Hence a better error message can be : -
("Loops are not allowed . Adding the edge from (%s->%s) forms a loop" % (v,u))

**Comment by abinash-panda** [comment]
@palashahuja This error message is correct. Send a PR making the changes.

**Comment by abinash-panda** [comment]
@palashahuja Please don't close the PR until its merged. It would be better to have all the comments and changes in a single PR.
