### ISSUE TITLE
Bug in VariableElimination

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#396]
``` python
cpd_accident = TabularCPD('accident', 2, [[0.2], [0.8]])

cpd_traffic_jam = TabularCPD('traffic_jam', 2, [[0.9, 0.6, 0.7, 0.1],[0.1, 0.4, 0.3, 0.9]], evidence=['rain', 'accident'], evidence_card=[2, 2])

cpd_long_queues = TabularCPD('long_queues', 2, [[0.9, 0.2], [0.1, 0.8]], evidence=['traffic_jam'], evidence_card=[2])

cpd_getting_up_late = TabularCPD('getting_up_late', 2, [[0.6], [0.4]])

cpd_late_for_school = TabularCPD('late_for_school', 2, [[0.9, 0.45, 0.8, 0.1], [0.1, 0.55, 0.2, 0.9]], evidence=['getting_up_late', 'traffic_jam'], evidence_card=[2, 2])

cpd_rain = TabularCPD('rain', 2, [[0.4], [0.6]])

model = BayesianModel([('accident', 'traffic_jam'), ('rain', 'traffic_jam'), ('traffic_jam', 'late_for_school'), ('traffic_jam', 'long_queues'), ('getting_up_late', 'late_for_school')])

model.add_cpds(cpd_accident, cpd_traffic_jam, cpd_long_queues, cpd_getting_up_late, cpd_late_for_school, cpd_rain)

from pgmpy.inference import VariableElimination

infer = VariableElimination(model)

infer.query(['rain'], evidence={'traffic_jam': 1})

Traceback (most recent call last):

  File "<ipython-input-29-75d9f03ac72c>", line 1, in <module>
    infer.query(['rain'], evidence={'traffic_jam': 1})

  File "/home/ankur/pgmpy/pgmpy/inference/ExactInference.py", line 120, in query
    evidence=evidence, elimination_order=elimination_order)

  File "/home/ankur/pgmpy/pgmpy/inference/ExactInference.py", line 49, in _variable_elimination
    inplace=False)

  File "/home/ankur/pgmpy/pgmpy/factors/Factor.py", line 274, in reduce
    value_indices = list(map(int, value_row[1]))

ValueError: invalid literal for int() with base 10: 'jam'
```

Happening because of our internal representation of variable with states (var_state) and since the variable name here is `traffic_jam`, it's splitting it from here.

https://github.com/pgmpy/pgmpy/issues/392 should fix this also.

**Comment by ankurankan** [comment]
Fixed in #407
