### ISSUE TITLE
factor reduce bug

### ISSUE THREAD

**Issue by palashahuja** [pgmpy/pgmpy#461]
The factor reduce does not seem to work when the variables are in tuple form.

```
>>> phi = Factor([('a', 0),('b', 0),('c', 0)], [2,2,2], list(range(8)))
>>> phi = phi.reduce((('a', 0), 0), inplace=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/palash/pgmpy/pgmpy/factors/Factor.py", line 296, in reduce
    return Factor(new_vars, new_card, new_values)
  File "/home/palash/pgmpy/pgmpy/factors/Factor.py", line 77, in __init__
    self.variables[variable] = [State(variable, index) for index in range(card)]
  File "/home/palash/anaconda3/lib/python3.4/collections/__init__.py", line 67, in __setitem__
    if key not in self:
TypeError: unhashable type: 'numpy.ndarray'
```

**Comment by palashahuja** [comment]
fixed ..
