### ISSUE TITLE
printing factor gives error when variables are in tuple form

### ISSUE THREAD

**Issue by palashahuja** [pgmpy/pgmpy#462]
```
>>> phi = Factor([('a', 0),('b', 0),('c', 0)], [2,2,2], list(range(8)))
>>> print(phi)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/palash/pgmpy/pgmpy/factors/Factor.py", line 428, in __str__
    return self._str(phi_or_p='phi', html=False)
  File "/home/palash/pgmpy/pgmpy/factors/Factor.py", line 446, in _str
    variables=','.join(string_header)))
TypeError: sequence item 0: expected str instance, tuple found
```

**Comment by palashahuja** [comment]
fixed ...
