### ISSUE TITLE
Unable to finish install

### ISSUE THREAD

**Issue by ThomasHoppe** [pgmpy/pgmpy#468]
During python.exe setup.py install, I get the following error on a Windows machine running
Python 3.3.2 (v3.3.2:d047928ae3f6, May 16 2013, 00:06:53) [MSC v.1600 64 bit (AMD64)] on win32:
...
Using c:\python33\lib\site-packages
Searching for requests==2.7.0
Best match: requests 2.7.0
Processing requests-2.7.0-py3.3.egg
requests 2.7.0 is already the active version in easy-install.pth

Using c:\python33\lib\site-packages\requests-2.7.0-py3.3.egg
Searching for coverage==4.0b1
Best match: coverage 4.0b1
Processing coverage-4.0b1-py3.3-win-amd64.egg
coverage 4.0b1 is already the active version in easy-install.pth
Installing coverage-3.3-script.py script to c:\Python33\Scripts
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    "coveralls >= 0.4"
  File "c:\Python33\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\Python33\lib\distutils\dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "c:\Python33\lib\distutils\dist.py", line 948, in run_command
    cmd_obj.run()
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\install.py", line
74, in run
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\install.py", line
97, in do_egg_install
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\easy_install.py",
line 358, in run
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\easy_install.py",
line 574, in easy_install
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\easy_install.py",
line 625, in install_item
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\easy_install.py",
line 688, in process_distribution
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\easy_install.py",
line 593, in easy_install
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\easy_install.py",
line 628, in install_item
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\easy_install.py",
line 648, in process_distribution
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\setuptools\command\easy_install.py",
line 528, in install_egg_scripts
  File "c:\Python33\lib\site-packages\setuptools-2.2-py3.3.egg\pkg_resources.py", line 1326, in get_
metadata
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

Unclear for me from where this originates

**Comment by ankurankan** [comment]
We currently don't support windows. And since it works fine on Linux, I
guess this is a windows specific problem and don't know why it's happening.

Ankur

**Comment by ThomasHoppe** [comment]
If I comment out the "coveralls >= 0.4" line in setup.py, I don't get the error. So it seems to be related to this module. Is coveralls needed for running he pgmpy code? Or is it just required for development purposes?

**Comment by ankurankan** [comment]
It's for development only..

**Comment by ThomasHoppe** [comment]
Thanks. I suggest, that this should be documented.

**Comment by ankurankan** [comment]
Yeah, it should be. Better I will remove the modules which are needed only
for development.

**Comment by ankurankan** [comment]
Fixed in #469
