### ISSUE TITLE
Error while running nosetests for testBayesianModelSampling.py

### ISSUE THREAD

**Issue by khalibartan** [pgmpy/pgmpy#508]
```
(testing2)➜  pgmpy git:(dev) nosetests
..................................................................................................................SS...E.SS....SS...............................................................................................................................................................................................................................................SSSSSSSSSS
======================================================================
ERROR: test_rejection_sample_basic (pgmpy.tests.test_inference.test_Sampling.TestBayesianModelSampling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/utgup/pgmpy/pgmpy/tests/test_inference/test_Sampling.py", line 56, in test_rejection_sample_basic
    sample = self.sampling_inference.rejection_sample([State('A', 1), State('J', 1), State('R', 1)], 25)
  File "/home/utgup/pgmpy/pgmpy/inference/Sampling.py", line 130, in rejection_sample
    _sampled = _sampled[_sampled.ix[:, evid.var] == evid]
  File "/home/utgup/anaconda3/envs/testing2/lib/python2.7/site-packages/pandas/core/ops.py", line 726, in wrapper
    res = na_op(values, other)
  File "/home/utgup/anaconda3/envs/testing2/lib/python2.7/site-packages/pandas/core/ops.py", line 644, in na_op
    result = lib.vec_compare(x, y.astype(np.object_), op)
  File "pandas/lib.pyx", line 801, in pandas.lib.vec_compare (pandas/lib.c:14361)
ValueError: Arrays were different lengths: 37 vs 2

----------------------------------------------------------------------
Ran 378 tests in 21.883s

FAILED (SKIP=16, errors=1)
```

I ran the nosetests in an conda environment with just pgmpy required packages. And I got following error. Here is my conda env info

```
(testing2)➜  pgmpy git:(dev) ✗ conda list
# packages in environment at /home/utgup/anaconda3/envs/testing2:
#
anaconda-client           1.1.2                    py27_0  
clyent                    1.0.0                    py27_0  
coverage                  4.0.1                     <pip>
coveralls                 1.1                       <pip>
decorator                 4.0.4                    py27_0  
docopt                    0.6.2                     <pip>
freetype                  2.5.5                         0  
funcsigs                  0.4                      py27_0  
jpeg                      8d                            0  
libgfortran               1.0                           0  
libpng                    1.6.17                        0  
libtiff                   4.0.6                         0  
mock                      1.3.0                    py27_0  
networkx                  1.10                     py27_0  
nose                      1.3.7                     <pip>
numpy                     1.10.1                   py27_0  
openblas                  0.2.14                        3  
openssl                   1.0.2d                        0  
pandas                    0.17.0              np110py27_0  
pbr                       1.3.0                    py27_0  
pgmpy                     0.1.0                     <pip>
pillow                    3.0.0                    py27_1  
pip                       7.1.2                    py27_0  
pyparsing                 2.0.3                    py27_0  
python                    2.7.10                        2  
python-dateutil           2.4.2                    py27_0  
pytz                      2015.6                   py27_0  
pyyaml                    3.11                     py27_1  
readline                  6.2                           2  
requests                  2.8.1                    py27_0  
scipy                     0.16.0              np110py27_1  
setuptools                18.4                     py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.8.4.1                       1  
tk                        8.5.18                        0  
wheel                     0.26.0                   py27_1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         0  
```

**Comment by ankurankan** [comment]
@khalibartan It's because you are using pandas 0.17.0. You can check in the `requirements.txt` that we support pandas 0.16.2. 
I will fix this so that it works with 0.17.0.
