### ISSUE TITLE
Upgrade pandas to 0.17.0

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#509]
Getting this error in tests on pandas 0.17.0:

``` python
======================================================================
ERROR: test_rejection_sample_basic (pgmpy.tests.test_inference.test_Sampling.TestBayesianModelSampling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ankur/pgmpy/pgmpy/tests/test_inference/test_Sampling.py", line 56, in test_rejection_sample_basic
    sample = self.sampling_inference.rejection_sample([State('A', 1), State('J', 1), State('R', 1)], 25)
  File "/home/ankur/pgmpy/pgmpy/inference/Sampling.py", line 130, in rejection_sample
    _sampled = _sampled[_sampled.ix[:, evid.var] == evid]
  File "/home/ankur/anaconda3/envs/py2/lib/python2.7/site-packages/pandas/core/ops.py", line 726, in wrapper
    res = na_op(values, other)
  File "/home/ankur/anaconda3/envs/py2/lib/python2.7/site-packages/pandas/core/ops.py", line 644, in na_op
    result = lib.vec_compare(x, y.astype(np.object_), op)
  File "pandas/lib.pyx", line 801, in pandas.lib.vec_compare (pandas/lib.c:14361)
ValueError: Arrays were different lengths: 37 vs 2

----------------------------------------------------------------------
Ran 378 tests in 17.882s

```

**Comment by ankurankan** [comment]
Known bug in pandas. Will be fixed in 0.17.1.

**Comment by eyadsibai** [comment]
they have released 0.17.1

**Comment by ankurankan** [comment]
Released 0.17.1 version is causing some bugs in pgmpy. We will discuss it 
whether the change needs to be done or not.

**Comment by khalibartan** [comment]
My bad for this, comment . I didn't checked the version details properly (confused between 0.17.0 and 0.17.1 ). Dependencies has been upgraded .

**Comment by khalibartan** [comment]
@ankurankan Close this issue .

**Comment by ankurankan** [comment]
@khalibartan Pandas 0.17.1 conflicts with python 3.3 (https://travis-ci.org/ankurankan/pgmpy/builds/98056983). So we will have to make some changes in `.travis.yml` to install different version of pandas for different python versions and similar changes in `setup.py`.

**Comment by khalibartan** [comment]
@ankurankan Okay. I didn't checked it out for python 3.3 .
