### ISSUE TITLE
i get error while testing code

### ISSUE THREAD

**Issue by RajuPilani** [pgmpy/pgmpy#568]
```
(pgmpy-env)pgmpy # nosetests3
...........................................................................................................................E...............................................................................................................E.............................................................................................................................................
======================================================================
ERROR: Failure: ImportError (cannot import name 'wraps')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/joseph/pgmpy/tests/test_inference/test_Sampling.py", line 3, in <module>
    from mock import MagicMock, patch
  File "/usr/local/lib/python3.4/dist-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/local/lib/python3.4/dist-packages/mock/mock.py", line 68, in <module>
    from six import wraps
ImportError: cannot import name 'wraps'

======================================================================
ERROR: Failure: ImportError (cannot import name 'wraps')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/joseph/pgmpy/tests/test_models/test_MarkovChain.py", line 6, in <module>
    from mock import patch, call
  File "/usr/local/lib/python3.4/dist-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/usr/local/lib/python3.4/dist-packages/mock/mock.py", line 68, in <module>
    from six import wraps
ImportError: cannot import name 'wraps'

----------------------------------------------------------------------
Ran 377 tests in 14.790s

FAILED (errors=2)
```

**Comment by RajuPilani** [comment]
i think problem is between "setuptools==19.2" version and "mock==1.3.0"

**Comment by khalibartan** [comment]
@RajuPilani try reinstalling pgmpy, with setup.py . Our tests are running fine. Send your package versions of env. (PS : `conda list`).

 `mock` version is okay and `setuptools` won't effect tests.
Are you sure that `mock` version is _1.3.0_

**Comment by RajuPilani** [comment]
reinstalling pgmpy with setup.py  but get same error in both conda env when run >>>nosetests3 

```
when i doing with python3.4 conda env "pgmpy-env"
```

```
(pgmpy-env) pgmpy # conda list
# packages in environment at /root/miniconda3/envs/pgmpy-env:
#
coverage                  4.1b1                     <pip>
coveralls                 1.1                       <pip>
decorator                 4.0.6                    py34_0  
docopt                    0.6.2                     <pip>
funcsigs                  0.4                      py34_0  
libgfortran               1.0                           0  
mock                      1.3.0                    py34_0  
networkx                  1.9.1                    py34_0  
nose                      1.3.7                     <pip>
numpy                     1.9.2                    py34_2  
openblas                  0.2.14                        3  
openssl                   1.0.2d                        0  
pandas                    0.16.2               np19py34_0  
pbr                       1.3.0                    py34_0  
pgmpy                     0.1.0                     <pip>
pip                       7.1.2                    py34_0  
pyparsing                 2.0.3                    py34_0  
python                    3.4.3                         2  
python-dateutil           2.4.2                    py34_0  
pytz                      2015.7                   py34_0  
readline                  6.2                           2  
requests                  2.9.1                     <pip>
scipy                     0.16.0               np19py34_1  
setuptools                19.1.1                   py34_0  
six                       1.10.0                   py34_0  
sqlite                    3.8.4.1                       1  
tk                        8.5.18                        0  
wheel                     0.26.0                   py34_1  
xz                        5.0.5                         0  
zlib                      1.2.8                         0  
```

```
when i doing with python3.3 conda env "pgmpy-env2"
```

```
(pgmpy-env2) pgmpy # conda list
# packages in environment at /root/miniconda3/envs/pgmpy-env2:
#
coverage                  4.1b1                     <pip>
coveralls                 1.1                       <pip>
decorator                 4.0.2                    py33_0  
docopt                    0.6.2                     <pip>
funcsigs                  0.4                      py33_0  
mock                      1.3.0                    py33_0  
networkx                  1.9.1                    py33_0  
nose                      1.3.7                     <pip>
numpy                     1.9.2                    py33_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py33_0  
pbr                       1.3.0                    py33_0  
pgmpy                     0.1.0                     <pip>
pip                       7.1.2                    py33_0  
pyparsing                 2.0.3                    py33_0  
python                    3.3.5                         4  
python-dateutil           2.4.2                    py33_0  
pytz                      2015.7                   py33_0  
readline                  6.2                           2  
requests                  2.9.1                     <pip>
scipy                     0.16.0               np19py33_0  
setuptools                19.1.1                   py33_0  
six                       1.10.0                   py33_0  
sqlite                    3.8.4.1                       1  
system                    5.8                           2  
tk                        8.5.18                        0  
wheel                     0.26.0                   py33_1  
xz                        5.0.5                         0  
zlib                      1.2.8                         0  
```

**Comment by RajuPilani** [comment]
when i run using 

```
>>> python setup.py test
```

in python3.4 (using pgmpy-env) i get error

```
======================================================================
ERROR: pgmpy.tests.test_readwrite.test_XMLBeliefNetwork (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/miniconda3/envs/pgmpy-env/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/root/miniconda3/envs/pgmpy-env/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/root/miniconda3/envs/pgmpy-env/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: pgmpy.tests.test_readwrite.test_XMLBeliefNetwork
Traceback (most recent call last):
  File "/root/miniconda3/envs/pgmpy-env/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/root/miniconda3/envs/pgmpy-env/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/home/joseph/pgmpy/__init__.py", line 1, in <module>
    from . import models
  File "/home/joseph/pgmpy/models/__init__.py", line 1, in <module>
    from .BayesianModel import BayesianModel
  File "/home/joseph/pgmpy/models/BayesianModel.py", line 8, in <module>
    import numpy as np
  File "/root/miniconda3/envs/pgmpy-env/lib/python3.4/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
ImportError: cannot import name 'add_newdocs'


----------------------------------------------------------------------
Ran 24 tests in 0.006s

FAILED (errors=24)
```

in python3.3 (using pgmpy-env2) ...pass all test

```
test_query_tighten_triplet_on (pgmpy.tests.test_inference.test_Mplp.TightenTripletOn) ... ok

----------------------------------------------------------------------
Ran 414 tests in 18.472s

OK
```

**Comment by khalibartan** [comment]
Ping @ankurankan

**Comment by ankurankan** [comment]
@RajuPilani I can't reproduce this. Can you share exactly the steps you are taking for installing ?

**Comment by RajuPilani** [comment]
my os :: Linux mint 17

```
now i get this type of error 
```

```
(pg34) ~/Desktop/raju/pgmpy/pgmpy $ nosetests3
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.4/site.py", line 586, in <module>
    main()
  File "/usr/lib/python3.4/site.py", line 572, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.4/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.4/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.4/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.4/sysconfig.py", line 602, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.4/sysconfig.py", line 545, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.4/sysconfig.py", line 417, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.4/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ImportError: No module named '_sysconfigdata_m'
```

my conda list ::::

```
(pg34)~/Desktop/raju/pgmpy/pgmpy $ conda list
# packages in environment at /home/raju/anaconda3/envs/pgmpy34:
#
abstract-rendering        0.5.1               np110py34_0  
alabaster                 0.7.6                    py34_0  
anaconda                  2.4.1               np110py34_0  
anaconda-client           1.2.1                    py34_0  
argcomplete               1.0.0                    py34_1  
astropy                   1.0.6               np110py34_0  
babel                     2.1.1                    py34_0  
backports-abc             0.4                       <pip>
backports_abc             0.4                      py34_0  
beautifulsoup4            4.4.1                    py34_0  
bitarray                  0.8.1                    py34_0  
blaze                     0.8.3                     <pip>
blaze-core                0.8.3                    py34_0  
bokeh                     0.10.0                   py34_0  
boto                      2.38.0                   py34_0  
bottleneck                1.0.0               np110py34_0  
cffi                      1.2.1                    py34_0  
clyent                    1.2.0                    py34_0  
colorama                  0.3.3                    py34_0  
configobj                 5.0.6                    py34_0  
coverage                  4.1b1                     <pip>
coveralls                 1.1                       <pip>
cryptography              1.0.2                    py34_0  
curl                      7.45.0                        0  
cycler                    0.9.0                    py34_0  
cython                    0.23.4                   py34_0  
cytoolz                   0.7.4                    py34_0  
datashape                 0.4.7               np110py34_1  
decorator                 4.0.6                    py34_0  
docopt                    0.6.2                     <pip>
docutils                  0.12                     py34_0  
fastcache                 1.0.2                    py34_0  
flask                     0.10.1                   py34_1  
fontconfig                2.11.1                        5  
freetype                  2.5.5                         0  
funcsigs                  0.4                      py34_0  
greenlet                  0.4.9                    py34_0  
h5py                      2.5.0               np110py34_4  
hdf5                      1.8.15.1                      2  
idna                      2.0                      py34_0  
ipykernel                 4.1.1                    py34_0  
ipython                   4.0.1                    py34_0  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py34_0  
ipython-qtconsole         4.0.1                    py34_0  
ipython_genutils          0.1.0                    py34_0  
ipywidgets                4.1.0                    py34_0  
itsdangerous              0.24                     py34_0  
jbig                      2.1                           0  
jdcal                     1.0                      py34_0  
jedi                      0.9.0                    py34_0  
jinja2                    2.8                      py34_0  
jpeg                      8d                            0  
jsonschema                2.4.0                    py34_0  
jupyter                   1.0.0                    py34_1  
jupyter-client            4.1.1                     <pip>
jupyter-console           4.0.3                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py34_0  
jupyter_console           4.0.3                    py34_0  
jupyter_core              4.0.6                    py34_0  
libffi                    3.0.13                        0  
libgfortran               1.0                           0  
libpng                    1.6.17                        0  
libsodium                 1.0.3                         0  
libtiff                   4.0.6                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.8.0                    py34_0  
lxml                      3.4.4                    py34_0  
markupsafe                0.23                     py34_0  
matplotlib                1.5.0               np110py34_0  
mistune                   0.7.1                    py34_0  
mock                      1.3.0                    py34_0  
multipledispatch          0.4.8                    py34_0  
nbconvert                 4.0.0                    py34_0  
nbformat                  4.0.1                    py34_0  
networkx                  1.9.1                    py34_0  
nltk                      3.1                      py34_0  
nose                      1.3.7                    py34_0  
notebook                  4.0.6                    py34_0  
numba                     0.22.1              np110py34_0  
numexpr                   2.4.4               np110py34_0  
numpy                     1.9.2                    py34_2  
odo                       0.3.4                    py34_0  
openblas                  0.2.14                        3  
openpyxl                  2.2.6                    py34_0  
openssl                   1.0.2e                        0  
pandas                    0.16.2               np19py34_0  
patchelf                  0.6                           0  
path.py                   8.1.2                    py34_1  
patsy                     0.4.0               np110py34_0  
pbr                       1.3.0                    py34_0  
pep8                      1.6.2                    py34_0  
pexpect                   3.3                      py34_0  
pgmpy                     0.1.0                     <pip>
pickleshare               0.5                      py34_0  
pillow                    3.0.0                    py34_1  
pip                       7.1.2                    py34_0  
ply                       3.8                      py34_0  
psutil                    3.3.0                    py34_0  
ptyprocess                0.5                      py34_0  
py                        1.4.30                   py34_0  
pyasn1                    0.1.9                    py34_0  
pycosat                   0.6.1                    py34_0  
pycparser                 2.14                     py34_0  
pycrypto                  2.6.1                    py34_0  
pycurl                    7.19.5.1                 py34_3  
pyflakes                  1.0.0                    py34_0  
pygments                  2.0.2                    py34_0  
pyopenssl                 0.15.1                   py34_1  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.11.4                   py34_1  
pytables                  3.2.2               np110py34_0  
pytest                    2.8.1                    py34_0  
python                    3.4.4                         0  
python-dateutil           2.4.2                    py34_0  
pytz                      2015.7                   py34_0  
pyyaml                    3.11                     py34_1  
pyzmq                     14.7.0                   py34_1  
qt                        4.8.7                         1  
qtconsole                 4.1.1                    py34_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py34_0  
requests                  2.8.1                    py34_0  
rope                      0.9.4                    py34_1  
rope-py3k-0.9.4           1                         <pip>
scikit-image              0.11.3              np110py34_0  
scikit-learn              0.17                np110py34_1  
scipy                     0.16.0               np19py34_1  
setuptools                19.1.1                   py34_0  
simplegeneric             0.8.1                    py34_0  
sip                       4.16.9                   py34_0  
six                       1.10.0                   py34_0  
snowballstemmer           1.2.0                    py34_0  
sockjs-tornado            1.0.1                    py34_0  
sphinx                    1.3.1                    py34_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py34_0  
spyder                    2.3.8                    py34_0  
spyder-app                2.3.8                    py34_0  
sqlalchemy                1.0.9                    py34_0  
sqlite                    3.9.2                         0  
statsmodels               0.6.1               np110py34_0  
sympy                     0.7.6.1                  py34_0  
tables                    3.2.2                     <pip>
terminado                 0.5                      py34_1  
theano                    0.7.0               np110py34_0  
tk                        8.5.18                        0  
toolz                     0.7.4                    py34_0  
tornado                   4.3                      py34_0  
traitlets                 4.0.0                    py34_0  
ujson                     1.33                     py34_0  
unicodecsv                0.14.1                   py34_0  
util-linux                2.21                          0  
werkzeug                  0.11.2                   py34_0  
wheel                     0.26.0                   py34_1  
xlrd                      0.9.4                    py34_0  
xlsxwriter                0.7.7                    py34_0  
xlwt                      1.0.0                    py34_0  
xz                        5.0.5                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         0 
```

**Comment by ankurankan** [comment]
@RajuPilani Can you tell me the exact steps you are taking to install ?

**Comment by RajuPilani** [comment]
```
>>> conda create -n pg34 python=3.4 anaconda
>>> source activate pg34
>>> conda install --file requirements.txt
>>> python setup.py install
```

**Comment by RajuPilani** [comment]
when i test using it's working fine

```
(pg34) ~/Desktop/raju/pgmpy/pgmpy $ python setup.py test 
.........................
...test_query_tighten_triplet_on (pgmpy.tests.test_inference.test_Mplp.TightenTripletOn) ... ok

----------------------------------------------------------------------
Ran 414 tests in 18.472s

OK
```

when i test using nosetest3 it's give me an error

```
(pg34) ~/Desktop/raju/pgmpy/pgmpy $ nosetests3
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.4/site.py", line 586, in <module>
    main()
  File "/usr/lib/python3.4/site.py", line 572, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.4/site.py", line 287, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python3.4/site.py", line 263, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python3.4/site.py", line 253, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python3.4/sysconfig.py", line 602, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python3.4/sysconfig.py", line 545, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python3.4/sysconfig.py", line 417, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python3.4/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_m import *
ImportError: No module named '_sysconfigdata_m'
```

**Comment by RajuPilani** [comment]
@ankurankan now i get above error only not previous "wraps" error.

**Comment by khalibartan** [comment]
@RajuPilani This not actually an error in pgmpy. Also I'm not able to reproduce this error.

**Comment by RajuPilani** [comment]
@khalibartan we can test our code with 

```
>>> python setup.py test
```

we need to test using ">>> nosetests3" is necessary

**Comment by khalibartan** [comment]
I don't know clearly but setup.py test option is to test your installation of pgmpy. But to run tests after changes in your local branch nosetests is used.

**Comment by RajuPilani** [comment]
now i get this error but networkx package already in my condalist 

```
(pg34) ~/Desktop/raju/pgmpy/pgmpy $ nosetests3
E
======================================================================
ERROR: Failure: ImportError (No module named 'networkx')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 411, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.4/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.4/imp.py", line 217, in load_package
    return methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/raju/pgmpy/__init__.py", line 1, in <module>
    from . import models
  File "/home/raju/pgmpy/models/__init__.py", line 1, in <module>
    from .BayesianModel import BayesianModel
  File "/home/raju/pgmpy/models/BayesianModel.py", line 7, in <module>
    import networkx as nx
ImportError: No module named 'networkx'

----------------------------------------------------------------------
Ran 1 test in 0.003s

FAILED (errors=1)

```

conda list :::

```
(pg34)~/Desktop/raju/pgmpy/pgmpy $ conda list
# packages in environment at /home/raju/anaconda3/envs/pgmpy34:
#
abstract-rendering        0.5.1               np110py34_0  
alabaster                 0.7.6                    py34_0  
anaconda                  2.4.1               np110py34_0  
anaconda-client           1.2.1                    py34_0  
argcomplete               1.0.0                    py34_1  
astropy                   1.0.6               np110py34_0  
babel                     2.1.1                    py34_0  
backports-abc             0.4                       <pip>
backports_abc             0.4                      py34_0  
beautifulsoup4            4.4.1                    py34_0  
bitarray                  0.8.1                    py34_0  
blaze                     0.8.3                     <pip>
blaze-core                0.8.3                    py34_0  
bokeh                     0.10.0                   py34_0  
boto                      2.38.0                   py34_0  
bottleneck                1.0.0               np110py34_0  
cffi                      1.2.1                    py34_0  
clyent                    1.2.0                    py34_0  
colorama                  0.3.3                    py34_0  
configobj                 5.0.6                    py34_0  
coverage                  4.1b1                     <pip>
coveralls                 1.1                       <pip>
cryptography              1.0.2                    py34_0  
curl                      7.45.0                        0  
cycler                    0.9.0                    py34_0  
cython                    0.23.4                   py34_0  
cytoolz                   0.7.4                    py34_0  
datashape                 0.4.7               np110py34_1  
decorator                 4.0.6                    py34_0  
docopt                    0.6.2                     <pip>
docutils                  0.12                     py34_0  
fastcache                 1.0.2                    py34_0  
flask                     0.10.1                   py34_1  
fontconfig                2.11.1                        5  
freetype                  2.5.5                         0  
funcsigs                  0.4                      py34_0  
greenlet                  0.4.9                    py34_0  
h5py                      2.5.0               np110py34_4  
hdf5                      1.8.15.1                      2  
idna                      2.0                      py34_0  
ipykernel                 4.1.1                    py34_0  
ipython                   4.0.1                    py34_0  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py34_0  
ipython-qtconsole         4.0.1                    py34_0  
ipython_genutils          0.1.0                    py34_0  
ipywidgets                4.1.0                    py34_0  
itsdangerous              0.24                     py34_0  
jbig                      2.1                           0  
jdcal                     1.0                      py34_0  
jedi                      0.9.0                    py34_0  
jinja2                    2.8                      py34_0  
jpeg                      8d                            0  
jsonschema                2.4.0                    py34_0  
jupyter                   1.0.0                    py34_1  
jupyter-client            4.1.1                     <pip>
jupyter-console           4.0.3                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py34_0  
jupyter_console           4.0.3                    py34_0  
jupyter_core              4.0.6                    py34_0  
libffi                    3.0.13                        0  
libgfortran               1.0                           0  
libpng                    1.6.17                        0  
libsodium                 1.0.3                         0  
libtiff                   4.0.6                         1  
libxml2                   2.9.2                         0  
libxslt                   1.1.28                        0  
llvmlite                  0.8.0                    py34_0  
lxml                      3.4.4                    py34_0  
markupsafe                0.23                     py34_0  
matplotlib                1.5.0               np110py34_0  
mistune                   0.7.1                    py34_0  
mock                      1.3.0                    py34_0  
multipledispatch          0.4.8                    py34_0  
nbconvert                 4.0.0                    py34_0  
nbformat                  4.0.1                    py34_0  
networkx                  1.9.1                    py34_0  
nltk                      3.1                      py34_0  
nose                      1.3.7                    py34_0  
notebook                  4.0.6                    py34_0  
numba                     0.22.1              np110py34_0  
numexpr                   2.4.4               np110py34_0  
numpy                     1.9.2                    py34_2  
odo                       0.3.4                    py34_0  
openblas                  0.2.14                        3  
openpyxl                  2.2.6                    py34_0  
openssl                   1.0.2e                        0  
pandas                    0.16.2               np19py34_0  
patchelf                  0.6                           0  
path.py                   8.1.2                    py34_1  
patsy                     0.4.0               np110py34_0  
pbr                       1.3.0                    py34_0  
pep8                      1.6.2                    py34_0  
pexpect                   3.3                      py34_0  
pgmpy                     0.1.0                     <pip>
pickleshare               0.5                      py34_0  
pillow                    3.0.0                    py34_1  
pip                       7.1.2                    py34_0  
ply                       3.8                      py34_0  
psutil                    3.3.0                    py34_0  
ptyprocess                0.5                      py34_0  
py                        1.4.30                   py34_0  
pyasn1                    0.1.9                    py34_0  
pycosat                   0.6.1                    py34_0  
pycparser                 2.14                     py34_0  
pycrypto                  2.6.1                    py34_0  
pycurl                    7.19.5.1                 py34_3  
pyflakes                  1.0.0                    py34_0  
pygments                  2.0.2                    py34_0  
pyopenssl                 0.15.1                   py34_1  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.11.4                   py34_1  
pytables                  3.2.2               np110py34_0  
pytest                    2.8.1                    py34_0  
python                    3.4.4                         0  
python-dateutil           2.4.2                    py34_0  
pytz                      2015.7                   py34_0  
pyyaml                    3.11                     py34_1  
pyzmq                     14.7.0                   py34_1  
qt                        4.8.7                         1  
qtconsole                 4.1.1                    py34_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py34_0  
requests                  2.8.1                    py34_0  
rope                      0.9.4                    py34_1  
rope-py3k-0.9.4           1                         <pip>
scikit-image              0.11.3              np110py34_0  
scikit-learn              0.17                np110py34_1  
scipy                     0.16.0               np19py34_1  
setuptools                19.1.1                   py34_0  
simplegeneric             0.8.1                    py34_0  
sip                       4.16.9                   py34_0  
six                       1.10.0                   py34_0  
snowballstemmer           1.2.0                    py34_0  
sockjs-tornado            1.0.1                    py34_0  
sphinx                    1.3.1                    py34_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py34_0  
spyder                    2.3.8                    py34_0  
spyder-app                2.3.8                    py34_0  
sqlalchemy                1.0.9                    py34_0  
sqlite                    3.9.2                         0  
statsmodels               0.6.1               np110py34_0  
sympy                     0.7.6.1                  py34_0  
tables                    3.2.2                     <pip>
terminado                 0.5                      py34_1  
theano                    0.7.0               np110py34_0  
tk                        8.5.18                        0  
toolz                     0.7.4                    py34_0  
tornado                   4.3                      py34_0  
traitlets                 4.0.0                    py34_0  
ujson                     1.33                     py34_0  
unicodecsv                0.14.1                   py34_0  
util-linux                2.21                          0  
werkzeug                  0.11.2                   py34_0  
wheel                     0.26.0                   py34_1  
xlrd                      0.9.4                    py34_0  
xlsxwriter                0.7.7                    py34_0  
xlwt                      1.0.0                    py34_0  
xz                        5.0.5                         0  
yaml                      0.1.6                         0  
zeromq                    4.1.3                         0  
zlib                      1.2.8                         0  

```

**Comment by ankurankan** [comment]
@RajuPilani Simply use `nosetests` to run the tests and since you are in a python3 env it will be using python 3. I will need to figure out why `nosetests` and `nosetests3` are giving different results.

**Comment by RajuPilani** [comment]
@ankurankan that's error happen because of when i run "nosetests3" in conda env but it's looking for local env mudules(numpy,pandas.etc) . when i install all modules in local env it's working "ok" but when i remove all modules from local env it's give me above "module import error". that's happen because of different path then what should i do ? it's make any problem ?

**Comment by khalibartan** [comment]
@RajuPilani  Actuall you need to install modules in your env. Or either you default env should contain pgmpy compatible modules and you can run than without using any env. We prefer python 3.4 but pgmpy in current state is compatible with 2.7 . If you have a anaconda package for python 2.7, 3.3, 3.4
you can run pgmpy without creating any env. Just run setup.py install and it will install pgmpy in conda.
