### ISSUE TITLE
ValueError: Values array must be of size:64

### ISSUE THREAD

**Issue by OKotevska** [pgmpy/pgmpy#573]
I'm having this error, any idea how it can be solved:
data = np.random.randint(low=0, high=4, size=(40, 4))

 raise ValueError("Values array must be of size: {size}".format(size=np.product(cardinality)))
ValueError: Values array must be of size: 64

**Comment by ankurankan** [comment]
@CloudDemo Can you share the whole code  and the complete traceback of the error ?

**Comment by khalibartan** [comment]
@CloudDemo Share the exact steps so that we can reproduce it. And moreover you may like to look at it https://guides.github.com/features/issues/

**Comment by OKotevska** [comment]
This is the program:

import numpy as np
import pandas as pd
from pgmpy.models import BayesianModel

data = np.random.randint(low=0, high=4, size=(40, 4))
data = pd.DataFrame(data, columns=['cost', 'quality', 'location', 'no_of_people'])

train = data[:32] 
test = data[32:].drop('no_of_people', axis=1)

restaurant_model = BayesianModel(
[('location', 'cost'),
('quality', 'cost'),
('location', 'no_of_people'),
('cost', 'no_of_people')])
restaurant_model.fit(train)

---

Traceback (most recent call last):

  File "<ipython-input-39-652112fbc3bb>", line 1, in <module>
    runfile('/home/onk3/UbuntuShared/pgm/pgm-4.py', wdir='/home/onk3/pgmpy')

  File "/home/onk3/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/home/onk3/anaconda3/lib/python3.5/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 88, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)

  File "/home/onk3/UbuntuShared/pgm/pgm-4.py", line 40, in <module>
    restaurant_model.fit(train)

  File "/home/onk3/pgmpy/pgmpy/models/BayesianModel.py", line 557, in fit
    cpds_list = estimator.get_parameters()

  File "/home/onk3/pgmpy/pgmpy/estimators/MLE.py", line 75, in get_parameters
    evidence_card=parent_card.astype('int'))

  File "/home/onk3/pgmpy/pgmpy/factors/CPD.py", line 139, in **init**
    super(TabularCPD, self).**init**(variables, cardinality, values.flatten('C'))

  File "/home/onk3/pgmpy/pgmpy/factors/Factor.py", line 104, in **init**
    raise ValueError("Values array must be of size: {size}".format(size=np.product(cardinality)))

ValueError: Values array must be of size: 64

**Comment by yashu-seth** [comment]
@CloudDemo I am looking into it. We will try to fix this as soon as possible.

**Comment by chrisittner** [comment]
Fixed in #667.
