### ISSUE TITLE
Repeated use of reduce and marginalize on same TabularCPD produces errors

### ISSUE THREAD

**Issue by anaviltripathi** [pgmpy/pgmpy#635]
If I repeatedly call reduce or marginalize on the same tabular CPD using different variables I get an error. I don't think this behavior is expected as I think reducing a CPD in one single call to reduce by providing all the variables and repeatedly calling reduce separately for each variable should produce the same output.

``` python
c = TabularCPD('grade', 3, [[0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
...                                             [0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
...                                             [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]],
...                                evidence=['intel', 'diff'], evidence_card=[3, 2])
>>> c.reduce([('intel', 0), ('diff', 0)])
>>> print(c)
+---------+---------+
| intel   | intel_0 |
+---------+---------+
| diff    | diff_0  |
+---------+---------+
| grade_0 | 0.1     |
+---------+---------+
| grade_1 | 0.1     |
+---------+---------+
| grade_2 | 0.8     |
+---------+---------+

>>> c = TabularCPD('grade', 3, [[0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
...                                            [0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
...                                            [0.8, 0.8, 0.8, 0.8, 0.8, 0.8]],
...                               evidence=['intel', 'diff'], evidence_card=[3, 2])


>>> c.reduce([('diff', 0)])
>>> c.reduce([('intel', 0)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgmpy/factors/CPD.py", line 348, in reduce
    super(TabularCPD, tabular_cpd).reduce(values)
  File "pgmpy/factors/Factor.py", line 432, in reduce
    phi.values = phi.values[tuple(slice_)]
IndexError: too many indices

```

It is the same case with `marginalize` method.

**Comment by yashu-seth** [comment]
``` python
>>> c = TabularCPD('grade', 3, [[1,2,3,4,5,6],
                [7,8,9,10,11,12],
                                [13,14,15,16,17,18]],evidence=['intel', 'diff'], evidence_card=[3, 2])
>>> c.normalize()
>>> print(c)
╒═════════╤══════════════════════╤═════════════════════╤════════════════════╤═════════════════════╤═════════════════════╤═════════════════════╕
│ intel   │ intel_0              │ intel_0             │ intel_1            │ intel_1             │ intel_2             │ intel_2             │
├─────────┼──────────────────────┼─────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┤
│ diff    │ diff_0               │ diff_1              │ diff_0             │ diff_1              │ diff_0              │ diff_1              │
├─────────┼──────────────────────┼─────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┤
│ grade_0 │ 0.047619047619047616 │ 0.08333333333333333 │ 0.1111111111111111 │ 0.13333333333333333 │ 0.15151515151515152 │ 0.16666666666666666 │
├─────────┼──────────────────────┼─────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┤
│ grade_1 │ 0.3333333333333333   │ 0.3333333333333333  │ 0.3333333333333333 │ 0.3333333333333333  │ 0.3333333333333333  │ 0.3333333333333333  │
├─────────┼──────────────────────┼─────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼─────────────────────┤
│ grade_2 │ 0.6190476190476191   │ 0.5833333333333334  │ 0.5555555555555556 │ 0.5333333333333333  │ 0.5151515151515151  │ 0.5                 │
╘═════════╧══════════════════════╧═════════════════════╧════════════════════╧═════════════════════╧═════════════════════╧═════════════════════╛
>>> c.reduce([('grade', 2)])
Traceback (most recent call last):
  File "<pyshell#43>", line 1, in <module>
    c.reduce([('grade', 2)])
  File "c:\work\pgmpy\pgmpy\factors\CPD.py", line 348, in reduce
    super(TabularCPD, tabular_cpd).reduce(values)
  File "c:\work\pgmpy\pgmpy\factors\Factor.py", line 432, in reduce
    phi.values = phi.values[tuple(slice_)]
IndexError: too many indices for array
```

**Comment by khalibartan** [comment]
Any leads on this. Is it because we are not updating the things or any other reasons. I am also getting same error as mentioned by @yashu-seth . We like if someone keeps me updated about this issue on this thread.

**Comment by yashu-seth** [comment]
@khalibartan I haven't looked into it yet. @anaviltripathi Did you find some reason behind this?

**Comment by anaviltripathi** [comment]
@yashu-seth @khalibartan I will update you on this tomorrow. In the meanwhile think about that other issue #628 of whether to allow reduce and marginalize for variable itself.

**Comment by anaviltripathi** [comment]
@yashu-seth @khalibartan Bug is actually in `normalize` method of TabularCPD. It is flattening the values array but not reshaping according to cardinalities. Both `reduce` and `marginalize` call `normalize` so this bug appears in both. 
Fix is easy and I will do it once other things are finalized.
