### ISSUE TITLE
Issue with the simple example in Mastering PGMs with Python - check_independence

### ISSUE THREAD

**Issue by Geof11061** [pgmpy/pgmpy#642]
Hi there

I have just got down pgmpy and am trying out the examples from this book. 

In the example that uses JointProbabilityDistribution, I run the following code

`In [16]: from pgmpy.factors import JointProbabilityDistribution as Joint
In [17]: distribution = Joint(['coin1', 'coin2'], 
                              [2, 2], 
                              [0.25, 0.25, 0.25, 0.25])`

this is fine and can print(distribution) without issues. However, running the following line:

`distribution.check_independence('coin1', 'coin2')`

produces the following error:

In[35]: distribution.check_independence('coin1', 'coin2')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-354efcfeff6c>", line 1, in <module>
    distribution.check_independence('coin1', 'coin2')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/JointProbabilityDistribution.py", line 153, in check_independence
    if (self.marginal_distribution(variable_pair, inplace=False) !=
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/JointProbabilityDistribution.py", line 121, in marginal_distribution
    inplace=inplace)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/Factor.py", line 209, in marginalize
    marginalized_values.append(np.sum(factor.values[factor._index_for_assignment(assign)]))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/Factor.py", line 416, in _index_for_assignment
    card_cumprod = np.delete(np.concatenate((np.array([1]), np.cumprod(self.cardinality[::-1])), axis=1)[::-1], 0)
**IndexError: axis 1 out of bounds [0, 1)**

Does anybody have any ideas what might be causing this? The above error occurs when run in PyCharm

When run in IPython, a different error occurs:
**
TypeError: Event 1 should be a list or array-like structure**

Thanks!

**Comment by khalibartan** [comment]
@Geof11061 Actually we don't allow events to be of string type. Try this
`distribution.check_independence(['coin1'], ['coin2'])`
This will work fine. Here is the output that I got

```
In [1]: from pgmpy.factors import JointProbabilityDistribution as Joint

In [2]: distribution = Joint(['coin1', 'coin2'], [2, 2], [0.25, 0.25, 0.25, 0.25])

In [3]: distribution.check_independence(['coin1'], ['coin2'])
Out[3]: True
```

Also use the updated version of pgmpy, your pycharm version of pgmpy is really old, we don't use that implementation any more. IPython is giving the correct error.

**Comment by Geof11061** [comment]
Thanks so much @khalibartan ! That works, and indeed it works in pycharm after updating! 

Thanks again!!!!

**Comment by khalibartan** [comment]
@Geof11061 If issue is fixed, then you can close this thread.
