### ISSUE TITLE
Error during installation 

### ISSUE THREAD

**Issue by ghost** [pgmpy/pgmpy#653]
I have install the `requirement.txt` successfully, but failed during the installation of the package. Here is the full traceback:

```
EOF
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    "coveralls >= 0.4"
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 342, in run
    self.easy_install(spec, not self.no_deps)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 562, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 614, in install_item
    self.process_distribution(spec, dist, deps)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 666, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 544, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 786, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 798, in obtain
    return installer(requirement)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 582, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 612, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 802, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 1079, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/easy_install.py", line 1068, in run_setup
    run_setup(setup_script, args)
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/sandbox.py", line 29, in run_setup
    lambda: execfile(
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/sandbox.py", line 70, in run
    return func()
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/sandbox.py", line 31, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 386, in <module>

  File "setup.py", line 378, in setup_package

  File "/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/easy_install-3OX7yB/numpy-1.11.0rc1/numpy/distutils/core.py", line 169, in setup
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/yobichi/hp/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/setuptools/command/bdist_egg.py", line 172, in run
    self.run_command("egg_info")
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/easy_install-3OX7yB/numpy-1.11.0rc1/numpy/distutils/command/egg_info.py", line 18, in run
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/easy_install-3OX7yB/numpy-1.11.0rc1/numpy/distutils/command/build_src.py", line 147, in run
  File "/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/easy_install-3OX7yB/numpy-1.11.0rc1/numpy/distutils/command/build_src.py", line 167, in build_sources
  File "/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/easy_install-3OX7yB/numpy-1.11.0rc1/numpy/distutils/command/build_src.py", line 256, in build_npy_pkg_config
AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by ghost** [comment]
After installing `mock` separately, I install the `setup.py` again but another error about the clang generated. But the nosetest has been passed. So does it mean that the model can be successfully implemented?

**Comment by ankurankan** [comment]
Can you please share the error that you got the second time?

**Comment by ghost** [comment]
@ankurankan  

``` bash
1 error generated.
/private/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/easy_install-663Sfz/numpy-1.11.0rc1/numpy/core/src/npymath/npy_math.c.src:56:10: fatal error: 'npy_math_private.h' file not found
#include "npy_math_private.h"
         ^
1 error generated.
error: Setup script exited with error: Command "clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/private/var/folders/dh/cyj9qhyj271945lvydyv5yr80000gn/T/easy_install-663Sfz/numpy-1.11.0rc1/numpy/core/include -Ibuild/src.macosx-10.10-x86_64-2.7/numpy/core/include/numpy -I/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/include/python2.7 -Ibuild/src.macosx-10.10-x86_64-2.7/numpy/core/src/private -Ibuild/src.macosx-10.10-x86_64-2.7/numpy/core/src/private -Ibuild/src.macosx-10.10-x86_64-2.7/numpy/core/src/private -c build/src.macosx-10.10-x86_64-2.7/numpy/core/src/npymath/npy_math.c -o build/temp.macosx-10.10-x86_64-2.7/build/src.macosx-10.10-x86_64-2.7/numpy/core/src/npymath/npy_math.o" failed with exit status 1
```

**Comment by ankurankan** [comment]
@rylanchiu Looks like a numpy issue. Can you try reinstalling numpy ? And also I would really suggest you to use anaconda if you are not using.

**Comment by ghost** [comment]
@ankurankan  I once used anaconda before but the independence are messed up finally and I had to reinstall the os. But i will try to reinstall the numpy, thanks.

**Comment by ghost** [comment]
@ankurankan  The error still exists after I reinstall the numpy. But I can import numpy and pgmpy successfully.

**Comment by sandeepkrjha** [comment]
``` python
In [1]: import pgmpy
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version a but this version of numpy is 9
```

This error is showing after I have installed all the dependencies. I upgraded numpy but still error is as it is .

**Comment by khalibartan** [comment]
Can you give details of environment , if you are using conda env then use `conda list`. I just freshly installed pgmpy as to check issues, but I got none.

**Comment by sandeepkrjha** [comment]
@khalibartan I am using virtual environment in conda.  

```
(pgmpy-env)sandeep@sandepp:~/pgmpy$ conda list
# packages in environment at /home/sandeep/anaconda3/envs/pgmpy-env:
#
anaconda-client           1.2.2                    py34_0  
clyent                    1.2.1                    py34_0  
openssl                   1.0.2g                        0  
pip                       8.0.3                    py34_0  
python                    3.4.4                         0  
python-dateutil           2.4.2                    py34_0  
pytz                      2015.7                   py34_0  
pyyaml                    3.11                     py34_1  
readline                  6.2                           2  
requests                  2.9.1                    py34_0  
setuptools                20.1.1                   py34_0  
six                       1.10.0                   py34_0  
sqlite                    3.9.2                         0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py34_0  
xz                        5.0.5                         1  
yaml                      0.1.6                         0  
zlib                      1.2.8       
```

installing requirements using conda gives this error.

```
(pgmpy-env)sandeep@sandepp:~/pgmpy$ conda install -f requirements.txtUsing Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Error: No packages found in current linux-64 channels matching: requirements.txt

You can search for this package on anaconda.org with

    anaconda search -t conda requirements.txt
(pgmpy-env)sandeep@sandepp:~/pgmpy$ anaconda search -t conda requirements.txt
Using Anaconda Cloud api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
No packages found
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
Found 0 packages
(pgmpy-env)sandeep@sandepp:~/pgmpy$ 
```

**Comment by khalibartan** [comment]
@sandeepkrjha the `-f` option is meant for force , use `--file` instead.

**Comment by sandeepkrjha** [comment]
@khalibartan  thanks. Its working fine now.
