### ISSUE TITLE
Correct error in tests

### ISSUE THREAD

**Issue by ankurankan** [pgmpy/pgmpy#72]
@abinashpanda, @gargshashank5 : Running tests gives this error:

```
E
======================================================================
ERROR: Failure: ImportError (No module named 'pgmpy.Factor._factor_product')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 38, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.3/imp.py", line 190, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.3/imp.py", line 160, in load_package
    return _bootstrap.SourceFileLoader(name, path).load_module(name)
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/ankur/pgmpy/pgmpy/__init__.py", line 1, in <module>
    from . import BayesianModel
  File "/home/ankur/pgmpy/pgmpy/BayesianModel/__init__.py", line 1, in <module>
    from .BayesianModel import *
  File "/home/ankur/pgmpy/pgmpy/BayesianModel/BayesianModel.py", line 8, in <module>
    from pgmpy.Factor import CPD
  File "/home/ankur/pgmpy/pgmpy/Factor/__init__.py", line 1, in <module>
    from .Factor import *
  File "/home/ankur/pgmpy/pgmpy/Factor/Factor.py", line 6, in <module>
    from pgmpy.Factor._factor_product import _factor_product
ImportError: No module named 'pgmpy.Factor._factor_product'

----------------------------------------------------------------------
Ran 1 test in 0.432s

FAILED (errors=1)
```

**Comment by ankurankan** [comment]
Use `sudo python3 setup.py develop` to generate .so file in the source directory.
