### ISSUE TITLE
install pgmpy in win10 with an error

### ISSUE THREAD

**Issue by weijy026a** [pgmpy/pgmpy#753]
when I install pgmpy with `python3 setup.py install`, it reports error as below:

```
...
...

Using d:\python\python35\lib\site-packages
Searching for coverage==4.2
Best match: coverage 4.2
Processing coverage-4.2-py3.5-win-amd64.egg
coverage 4.2 is already the active version in easy-install.pth
Installing coverage-3.5-script.py script to D:\Python\Python35\Scripts
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    "coveralls >= 0.4"
  File "D:\Python\Python35\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Python\Python35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Python\Python35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Python\Python35\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Python\Python35\lib\site-packages\setuptools\command\install.py", line 117, in do_egg_install
    cmd.run()
  File "D:\Python\Python35\lib\site-packages\setuptools\command\easy_install.py", line 391, in run
    self.easy_install(spec, not self.no_deps)
  File "D:\Python\Python35\lib\site-packages\setuptools\command\easy_install.py", line 621, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "D:\Python\Python35\lib\site-packages\setuptools\command\easy_install.py", line 672, in install_item
    self.process_distribution(spec, dist, deps)
  File "D:\Python\Python35\lib\site-packages\setuptools\command\easy_install.py", line 727, in process_distribution
    self.easy_install(dist.as_requirement())
  File "D:\Python\Python35\lib\site-packages\setuptools\command\easy_install.py", line 640, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "D:\Python\Python35\lib\site-packages\setuptools\command\easy_install.py", line 675, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "D:\Python\Python35\lib\site-packages\setuptools\command\easy_install.py", line 697, in process_distribution
    self.install_egg_scripts(dist)
  File "D:\Python\Python35\lib\site-packages\setuptools\command\easy_install.py", line 573, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "D:\Python\Python35\lib\site-packages\pkg_resources\__init__.py", line 1474, in get_metadata
    return self._get(self._fn(self.egg_info, name)).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

what should I do?

**Comment by ankurankan** [comment]
@weijy026a Seems like the issue is with `coverage` which is not required for using pgmpy. So, I have removed it from `setup.py`.  Can you please try to install the latest version of pgmpy again ? Also I would really recommend to use anaconda if you are not using it already.

**Comment by weijy026a** [comment]
It can be installed now. Thank you.
