### ISSUE TITLE
have installed pgmpy, but shows that "No module named wrapt"

### ISSUE THREAD

**Issue by pfzhan** [pgmpy/pgmpy#810]
I have cloned this project, and installed with "python setup.py install" on window10. Then, I went to cmd run python, and pasted "from pgmpy.models import BayesianModel", the result as seen below:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pgmpy\models\__init__.py", line 1, in <module>
    from .BayesianModel import BayesianModel
  File "pgmpy\models\BayesianModel.py", line 13, in <module>
    from pgmpy.factors.discrete import TabularCPD, JointProbabilityDistribution, DiscreteFactor
  File "pgmpy\factors\discrete\__init__.py", line 1, in <module>
    from .DiscreteFactor import State, DiscreteFactor, factor_product, factor_divide
  File "pgmpy\factors\discrete\DiscreteFactor.py", line 12, in <module>
    from pgmpy.utils import StateNameInit, StateNameDecorator
  File "pgmpy\utils\__init__.py", line 2, in <module>
    from .state_name import StateNameInit, StateNameDecorator
  File "pgmpy\utils\state_name.py", line 1, in <module>
    from wrapt import decorator
ImportError: No module named wrapt

**Comment by raghavg7796** [comment]
@dethrive You need to run 
`pip install -r requirements.txt  # or requirements-dev.txt if you want to run unittests`
or
`conda install --file requirements.txt  # or requirements-dev.txt if you want to run unittests
`
before actual setup. It will install wrapt.

**Comment by raghavg7796** [comment]
@ankurankan This can be closed.
