### ISSUE TITLE
distribution check_independence issue

### ISSUE THREAD

**Issue by Mary-Kul** [pgmpy/pgmpy#821]
Can you help, please? I have a code from 1st chapter of  your book -

```
from pgmpy.factors import JointProbabilityDistribution as Joint

distribution = Joint(['coin1', 'coin2'],
                     [2, 2],
                     [0.25, 0.25, 0.25, 0.25])
print(distribution.check_independence('coin1', 'coin2'))
```

it gives me the following error :

```
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    print(distribution.check_independence('coin1', 'coin2'))
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/JointProbabilityDistribution.py", line 153, in check_independence
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/JointProbabilityDistribution.py", line 121, in marginal_distribution
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/Factor.py", line 209, in marginalize
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/Factor.py", line 416, in _index_for_assignment
IndexError: axis 1 out of bounds [0, 1)
```

example from your docs:
```
from pgmpy.factors import TreeCPD, Factor
tree = TreeCPD([('B', Factor(['A'], [2], [0.8, 0.2]), '0'),
                ('B', 'C', '1'),
                ('C', Factor(['A'], [2], [0.1, 0.9]), '0'),
                ('C', 'D', '1'),
                ('D', Factor(['A'], [2], [0.9, 0.1]), '0'),
                ('D', Factor(['A'], [2], [0.4, 0.6]), '1')])
```

gives the same error

**Comment by raghavg7796** [comment]
@Mary-Kul I think you need to update the library. Mine is working fine.
```
from pgmpy.factors.discrete import JointProbabilityDistribution as Joint
distribution = Joint(['coin1', 'coin2'],
                     [2, 2],
                     [0.25, 0.25, 0.25, 0.25])
print(distribution.check_independence(['coin1'], ['coin2']))
```
gives True.
