### ISSUE TITLE
JointProbabilityDistribution failure

### ISSUE THREAD

**Issue by Pdogged** [pgmpy/pgmpy#849]
I'm currently going through the mastering probabilistic graphical models book and I'm experiencing two different failures associated with JointProbabilityDistribution.
First when I import the library
`from pgmpy.factors import JointProbabilityDistribution as Joint`
it returns this error
`TypeError: module.__init__() takes at most 2 arguments (3 given)`

I reinstalled using the instructions from github instead of the book,
 and from the following:
`from pgmpy.factors import JointProbabilityDistribution as Joint`

```
distribution = Joint(['coin1', 'coin2'],
                     [2, 2],
                     [0.25, 0.25, 0.25, 0.25])
```

`print(distribution.check_independence('coin1', 'coin2'))`

I receive this error

`Traceback (most recent call last):
  File "test.py", line 25, in <module>
    print(distribution.check_independence('coin1', 'coin2'))
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/JointProbabilityDistribution.py", line 153, in check_independence
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/JointProbabilityDistribution.py", line 121, in marginal_distribution
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/Factor.py", line 209, in marginalize
  File "/usr/local/lib/python3.5/site-packages/pgmpy-0.1.0-py3.5.egg/pgmpy/factors/Factor.py", line 416, in _index_for_assignment
IndexError: axis 1 out of bounds [0, 1)`

I tried this both on a Mac and a Linux box and received the same errors.

**Comment by khalibartan** [comment]
@Pdogged You should get an import error since JointProbabilityDistribution is in pgmpy.factors.discrete . Did you use pip install pgmpy ? Or are you using our latest dev branch ?

**Comment by Pdogged** [comment]
I'm using the non-dev branch, currently.
I was going by the mastering PGM using python book, which didn't stipulate .discrete.  I have since looked at pgmpy's docs and its now importing correctly.  
Also, I want to make sure that using it correctly.  
When using the book code 
`print(distribution.check_independence('coin1', 'coin2'))`
I receive this error:
`TypeError: Event 1 should be a list or array-like structure`
Checking the docs it seems I'm supposed to correct it with this:
`distribution.check_independence(['coin1'], ['coin2'])`
Which outputs True.  But I would just like to verify this.

Thank you for your help
