### ISSUE TITLE
Add tests for TabularCPD.__str__

### ISSUE THREAD

**Issue by lohani2280** [pgmpy/pgmpy#919]
Add tests for the issue below:

---------------------------------------------------------------------

### Subject of the issue
Error while printing CPD.

### Your environment
* version of pgmpy-0.1.6
* OS-Ubuntu 16.04

### Steps to reproduce
```
from pgmpy.models import DynamicBayesianNetwork as DBN
from pgmpy.factors.discrete import TabularCPD
from pgmpy.inference.dbn_inference import DBNInference 

dbn = DBN()

dbn.add_nodes_from(['A', 'B', 'C'])

dbn.add_edges_from([(('B', 0), ('A', 0)), (('C', 0), ('B', 0)), (('C', 0), ('A', 0)), 
                    (('C', 0), ('C', 1))])

C_cpd = TabularCPD(('C', 0), 3, [[0.0714286, 0.307143, 0.621429]])

A_cpd = TabularCPD(('A', 0), 2, [[0.5, 0.0, 1.0, 0.0, 0.456140350877, 0.5],
                                 [0.5, 1.0, 0.0, 1.0, 0.543859649123, 0.5]],
                   evidence=[('C', 0),('B', 0)],
                   evidence_card=[3,2])

B_cpd = TabularCPD(('B', 0), 2, [[0.0, 0.219512195122, 1.0],
                                 [1.0, 0.780487804878, 0.0]],
                   evidence=[('C', 0)],
                   evidence_card=[3])

C1_cpd = TabularCPD(('C', 1), 3, [[0.1, 0.0813953488372, 0.0862068965517],
                                  [0.3, 0.279069767442, 0.241379310345],
                                  [0.6, 0.639534883721, 0.672413793103]],
                    evidence=[('C', 0)],
                    evidence_card=[3])

print(C_cpd)

print(A_cpd)

print(B_cpd)
```
### Expected behaviour
>>
A tabular representation of A_cpd.

### Actual behaviour
>>> 
----------  ---------
('C', 0)_0  0.0714286
('C', 0)_1  0.307143
('C', 0)_2  0.621429
----------  ---------
Traceback (most recent call last):
  File "DBN_test.py", line 32, in <module>
    print(A_cpd)
  File "/home/lohani/open-source/pgmpy-foss/pgmpy-venv/lib/python3.5/site-packages/pgmpy-0.1.6-py3.5.egg/pgmpy/factors/discrete/CPD.py", line 175, in __str__
    return self._make_table_str("fancy_grid")
  File "/home/lohani/open-source/pgmpy-foss/pgmpy-venv/lib/python3.5/site-packages/pgmpy-0.1.6-py3.5.egg/pgmpy/factors/discrete/CPD.py", line 210, in _make_table_str
    cdf_str = tabulate(headers_list + labeled_rows, tablefmt=tablefmt)
  File "/home/lohani/open-source/pgmpy-foss/pgmpy-venv/lib/python3.5/site-packages/pgmpy-0.1.6-py3.5.egg/pgmpy/extern/tabulate.py", line 808, in tabulate
    coltypes = list(map(_column_type, cols))
  File "/home/lohani/open-source/pgmpy-foss/pgmpy-venv/lib/python3.5/site-packages/pgmpy-0.1.6-py3.5.egg/pgmpy/extern/tabulate.py", line 449, in _column_type
    types = [_type(s, has_invisible) for s in strings ]
  File "/home/lohani/open-source/pgmpy-foss/pgmpy-venv/lib/python3.5/site-packages/pgmpy-0.1.6-py3.5.egg/pgmpy/extern/tabulate.py", line 449, in <listcomp>
    types = [_type(s, has_invisible) for s in strings ]
  File "/home/lohani/open-source/pgmpy-foss/pgmpy-venv/lib/python3.5/site-packages/pgmpy-0.1.6-py3.5.egg/pgmpy/extern/tabulate.py", line 292, in _type
    elif _isnumber(string):
  File "/home/lohani/open-source/pgmpy-foss/pgmpy-venv/lib/python3.5/site-packages/pgmpy-0.1.6-py3.5.egg/pgmpy/extern/tabulate.py", line 251, in _isnumber
    return _isconvertible(float, string)
  File "/home/lohani/open-source/pgmpy-foss/pgmpy-venv/lib/python3.5/site-packages/pgmpy-0.1.6-py3.5.egg/pgmpy/extern/tabulate.py", line 236, in _isconvertible
    n = conv(string)
TypeError: float() argument must be a string or a number, not 'tuple'

**Comment by khalibartan** [comment]
@lohani2280 It is running fine on my system(ubuntu 16.04), which is using latest dev. Here is the output
```
╒════════════╤═══════════╕
│ ('C', 0)_0 │ 0.0714286 │
├────────────┼───────────┤
│ ('C', 0)_1 │ 0.307143  │
├────────────┼───────────┤
│ ('C', 0)_2 │ 0.621429  │
╘════════════╧═══════════╛
╒════════════╤════════════╤════════════╤════════════╤════════════╤════════════════╤════════════╕
│ ('C', 0)   │ ('C', 0)_0 │ ('C', 0)_0 │ ('C', 0)_1 │ ('C', 0)_1 │ ('C', 0)_2     │ ('C', 0)_2 │
├────────────┼────────────┼────────────┼────────────┼────────────┼────────────────┼────────────┤
│ ('B', 0)   │ ('B', 0)_0 │ ('B', 0)_1 │ ('B', 0)_0 │ ('B', 0)_1 │ ('B', 0)_0     │ ('B', 0)_1 │
├────────────┼────────────┼────────────┼────────────┼────────────┼────────────────┼────────────┤
│ ('A', 0)_0 │ 0.5        │ 0.0        │ 1.0        │ 0.0        │ 0.456140350877 │ 0.5        │
├────────────┼────────────┼────────────┼────────────┼────────────┼────────────────┼────────────┤
│ ('A', 0)_1 │ 0.5        │ 1.0        │ 0.0        │ 1.0        │ 0.543859649123 │ 0.5        │
╘════════════╧════════════╧════════════╧════════════╧════════════╧════════════════╧════════════╛
╒════════════╤════════════╤════════════════╤════════════╕
│ ('C', 0)   │ ('C', 0)_0 │ ('C', 0)_1     │ ('C', 0)_2 │
├────────────┼────────────┼────────────────┼────────────┤
│ ('B', 0)_0 │ 0.0        │ 0.219512195122 │ 1.0        │
├────────────┼────────────┼────────────────┼────────────┤
│ ('B', 0)_1 │ 1.0        │ 0.780487804878 │ 0.0        │
╘════════════╧════════════╧════════════════╧════════════╛
```

**Comment by lohani2280** [comment]
@khalibartan I don't know what's happening but i am still getting the same error.

**Comment by lohani2280** [comment]
@ankurankan Can you please cross-check once on your system too? .

**Comment by ankurankan** [comment]
@lohani2280 @khalibartan This happened because I recently updated tabulate (https://github.com/pgmpy/pgmpy/commit/9a543e860b29772b3680952d6282477fced90b33) and it has breaking back support. I have fixed it now, give it a try.

**Comment by lohani2280** [comment]
@ankurankan  Printing the CPD works fine now . However, while printing `factors` created using `DiscreteFactor` class , i found they are not being properly tabulated.

**Comment by ankurankan** [comment]
@lohani2280 Could you please create another issue for that ?

**Comment by lohani2280** [comment]
@ankurankan Yeah sure

**Comment by nags0x** [comment]
@ankurankan ig this will be my next shot :)

**Comment by biga-codes** [comment]
@ankurankan Hi! I would love to work on this, may I be assigned this issue if it's still up for grabs?

**Comment by Jay2006sawant** [comment]
Hey @nags0x ! Any updates on [this](https://github.com/pgmpy/pgmpy/pull/2118) or else should I look into this issue?

**Comment by jonuhl** [comment]
Hi @ankurankan! 👋

I see that this issue has been stale for some time. Could you assign me?

My planned solution:
- write a test test__str__ under TestTabularCPDMethods that asserts correct string outputs by comparing full strings
- implement four test scenarios that cover normal vs. tuple variables, evidence vs. no evidence and state names vs. auto-assigned names

**Comment by ankurankan** [comment]
@jonuhl Sorry, for the delay. Assigning it to you.

**Comment by jonuhl** [comment]
@ankurankan Thanks for assigning this to me! Would you have time to review it whenever it's convenient? :)
